# Generated by Django 5.2.10 on 2026-01-21 05:10

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B2BBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='B2BShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft - Editable'), ('locked', 'Locked - Labels Generated'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='draft', help_text='Draft = editable, Locked = read-only after labels generated, In Transit = shipped, Delivered = completed', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Timestamp when shipment was locked', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Timestamp when shipment was marked as delivered', null=True)),
                ('delivery_notes', models.TextField(blank=True, help_text='Notes about the delivery (signature, condition, etc.)')),
                ('delivery_proof', models.ImageField(blank=True, help_text='Photo proof of delivery (optional)', null=True, upload_to='shipment_delivery_proofs/')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cubic_m', models.DecimalField(blank=True, decimal_places=3, help_text='Cubic meters (m³)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('total_boxes', models.PositiveIntegerField(default=0)),
                ('material_type', models.CharField(choices=[('standard', 'Standard'), ('fragile', 'Fragile'), ('flammable', 'Flammable'), ('chemical', 'Dangerous Chemical'), ('perishable', 'Perishable')], default='standard', max_length=20)),
                ('material_class', models.CharField(blank=True, help_text='Optional material class (e.g. Class 3 Flammable Liquids)', max_length=80)),
                ('shipment_mode', models.CharField(choices=[('easy_move', 'Easy Move (Normal)'), ('cargo', 'Cargo'), ('air_freight', 'Air Freight')], default='easy_move', max_length=20)),
                ('shipping_company_name', models.CharField(blank=True, max_length=200)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('eta_text', models.CharField(blank=True, help_text='Estimated delivery time, e.g. 3-5 days', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2BShipmentBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('dimensions', models.CharField(blank=True, help_text='LxWxH in cm (optional)', max_length=50)),
                ('label', models.ImageField(blank=True, null=True, upload_to='b2b_shipments/box_labels/%Y/%m/%d/')),
                ('qr_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['shipment', 'box_number'],
            },
        ),
        migrations.CreateModel(
            name='B2BShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('quantity', models.PositiveIntegerField(help_text='Number of units packed in this box', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this item in the box', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Box Item',
                'verbose_name_plural': 'Box Items',
                'ordering': ['box', 'order_item'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active', verbose_name='Active')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deactivated', null=True, verbose_name='Deactivated At')),
                ('employee_id', models.CharField(blank=True, help_text='Unique employee identifier', max_length=20, unique=True, verbose_name='Employee ID')),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('license_number', models.CharField(help_text="Driver's license number", max_length=50, unique=True, verbose_name='License Number')),
                ('license_expiry', models.DateField(blank=True, help_text="Expiration date of driver's license", null=True, verbose_name='License Expiry Date')),
                ('date_hired', models.DateField(default=django.utils.timezone.now, help_text='Employment start date', verbose_name='Date Hired')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Emergency Contact Phone')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('speed_mps', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active', verbose_name='Active')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deactivated', null=True, verbose_name='Deactivated At')),
                ('name', models.CharField(help_text='Official name of the logistics office', max_length=100, verbose_name='Office Name')),
                ('location', models.CharField(help_text='Physical address or location description', max_length=255, verbose_name='Location')),
                ('code', models.CharField(blank=True, help_text='Unique identifier code (auto-generated if empty)', max_length=20, unique=True, verbose_name='Office Code')),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email for the office', max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact Phone')),
                ('timezone', models.CharField(default='UTC', help_text='Office timezone for scheduling operations', max_length=50, verbose_name='Timezone')),
            ],
            options={
                'verbose_name': 'Logistic Office',
                'verbose_name_plural': 'Logistic Offices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('shipment_number', models.PositiveIntegerField(default=1, help_text="Sequential number for this order's shipments")),
                ('tracking_number', models.CharField(blank=True, db_index=True, help_text='Unique tracking identifier', max_length=50, unique=True, verbose_name='Tracking Number')),
                ('collect_time', models.DateTimeField(help_text='Scheduled time for package collection', verbose_name='Collection Time')),
                ('estimated_dropoff_time', models.DateTimeField(help_text='Estimated delivery time', verbose_name='Estimated Dropoff Time')),
                ('actual_dropoff_time', models.DateTimeField(blank=True, help_text='Actual delivery completion time', null=True, verbose_name='Actual Dropoff Time')),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Total shipment weight in kilograms', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Weight (kg)')),
                ('size_cubic_meters', models.DecimalField(decimal_places=3, help_text='Total shipment volume in cubic meters', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Size (m³)')),
                ('material_type', models.CharField(choices=[('fragile', 'Fragile'), ('flammable', 'Flammable'), ('chemical', 'Dangerous Chemical'), ('perishable', 'Perishable'), ('standard', 'Standard')], db_index=True, default='standard', max_length=20, verbose_name='Material Type')),
                ('shipment_type', models.CharField(choices=[('express', 'Express'), ('normal', 'Normal'), ('economic', 'Economic'), ('free', 'Free'), ('same_day', 'Same Day')], db_index=True, default='normal', max_length=20, verbose_name='Shipment Type')),
                ('packing_type', models.CharField(choices=[('paper_box', 'Paper Box'), ('metal_box', 'Metal Box'), ('plastic_box', 'Plastic Box'), ('wooden_crate', 'Wooden Crate'), ('envelope', 'Envelope')], default='paper_box', max_length=20, verbose_name='Packing Type')),
                ('container_type', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('metal', 'Metal'), ('composite', 'Composite')], default='paper', max_length=20, verbose_name='Container Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('verification_photo', models.ImageField(blank=True, help_text='Photo proof of delivery', null=True, upload_to='shipments/verification/%Y/%m/%d/', verbose_name='Verification Photo')),
                ('delivery_notes', models.TextField(blank=True, help_text='Additional notes about the delivery', verbose_name='Delivery Notes')),
                ('special_instructions', models.TextField(blank=True, help_text='Special handling or delivery instructions', verbose_name='Special Instructions')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Shipping Cost')),
                ('created_by', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('box_number', models.PositiveIntegerField(help_text='Sequential number within the shipment', verbose_name='Box Number')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Weight (kg)')),
                ('dimensions', models.CharField(blank=True, help_text='Format: LxWxH in cm', max_length=50, verbose_name='Dimensions')),
                ('label', models.ImageField(blank=True, help_text='QR code label for the box', null=True, upload_to='shipments/box_labels/%Y/%m/%d/', verbose_name='Label')),
                ('qr_data', models.TextField(blank=True, help_text='Data encoded in the QR code', verbose_name='QR Data')),
            ],
            options={
                'verbose_name': 'Shipment Box',
                'verbose_name_plural': 'Shipment Boxes',
                'ordering': ['shipment', 'box_number'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shipment Item',
                'verbose_name_plural': 'Shipment Items',
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active', verbose_name='Active')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deactivated', null=True, verbose_name='Deactivated At')),
                ('plate_number', models.CharField(help_text='Vehicle license plate number', max_length=20, unique=True, verbose_name='Plate Number')),
                ('model', models.CharField(help_text='Vehicle make and model', max_length=50, verbose_name='Model')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Manufacturing year', null=True, verbose_name='Year')),
                ('capacity_kg', models.DecimalField(decimal_places=2, help_text='Maximum weight capacity in kilograms', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capacity (kg)')),
                ('capacity_cubic_meters', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum volume capacity in cubic meters', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capacity (m³)')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'Compressed Natural Gas')], default='gasoline', max_length=20, verbose_name='Fuel Type')),
                ('last_maintenance', models.DateField(blank=True, help_text='Date of last maintenance service', null=True, verbose_name='Last Maintenance')),
                ('next_maintenance', models.DateField(blank=True, help_text='Scheduled date for next maintenance', null=True, verbose_name='Next Maintenance')),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, unique=True, verbose_name='VIN')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active', verbose_name='Active')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was deactivated', null=True, verbose_name='Deactivated At')),
                ('name', models.CharField(help_text='Name of the warehouse facility', max_length=100, verbose_name='Warehouse Name')),
                ('code', models.CharField(blank=True, help_text='Unique warehouse identifier', max_length=20, unique=True, verbose_name='Warehouse Code')),
                ('address', models.TextField(help_text='Complete physical address of the warehouse', verbose_name='Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate', max_digits=9, null=True, verbose_name='Longitude')),
                ('capacity_cubic_meters', models.DecimalField(blank=True, decimal_places=2, help_text='Total storage capacity in cubic meters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capacity (m³)')),
                ('current_utilization', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current warehouse utilization percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Current Utilization (%)')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseShipmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('item_shipped', 'Item Shipped to Warehouse'), ('all_items_shipped', 'All Items Shipped'), ('shipment_created', 'Shipment Created')], default='item_shipped', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('items_count', models.PositiveIntegerField(default=1)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
