# Generated by Django 5.2.4 on 2025-07-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('orders', '0014_orderitem_shipped_to_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order'),
        ),
    ]
