# Generated by Django 5.2.10 on 2026-01-21 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        ('supply_chain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bboxitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_box_items', to='stores.b2borderitem'),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='company_config',
            field=models.ForeignKey(blank=True, help_text='Selected shipping company configuration based on origin + mode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_shipments', to='supply_chain.shippingcompanycountry'),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='delivered_by',
            field=models.ForeignKey(blank=True, help_text='User who marked shipment as delivered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='User who locked the shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_shipment', to='stores.b2border'),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_shipment', to='stores.b2bshippingaddress'),
        ),
        migrations.AddField(
            model_name='b2bshipmentbox',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='logistics.b2bshipment'),
        ),
        migrations.AddField(
            model_name='b2bboxitem',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.b2bshipmentbox'),
        ),
        migrations.AddField(
            model_name='b2bshipmentitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_shipment_items', to='stores.b2borderitem'),
        ),
        migrations.AddField(
            model_name='b2bshipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='logistics.b2bshipment'),
        ),
        migrations.AddField(
            model_name='boxitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_items', to='orders.orderitem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='logistics.driver'),
        ),
        migrations.AddIndex(
            model_name='logisticoffice',
            index=models.Index(fields=['code'], name='logistics_l_code_98a7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='logisticoffice',
            index=models.Index(fields=['is_active', 'name'], name='logistics_l_is_acti_e744f0_idx'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.driver', verbose_name='Assigned Driver'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='logistic_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.logisticoffice', verbose_name='Logistic Office'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.shippingaddress', verbose_name='Shipping Address'),
        ),
        migrations.AddField(
            model_name='shipmentbox',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='logistics.shipment', verbose_name='Shipment'),
        ),
        migrations.AddField(
            model_name='boxitem',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.shipmentbox', verbose_name='Box'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='logistics.shipment'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='logistics.driver', verbose_name='Assigned Driver'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.vehicle', verbose_name='Assigned Vehicle'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='logistic_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='logistics.logisticoffice', verbose_name='Logistic Office'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Warehouse Manager'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='warehouseshipmentnotification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_notifications', to='orders.order'),
        ),
        migrations.AddField(
            model_name='warehouseshipmentnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouseshipmentnotification',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_notifications', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='b2bshipment',
            index=models.Index(fields=['status', 'created_at'], name='logistics_b_status_288d55_idx'),
        ),
        migrations.AddIndex(
            model_name='b2bshipment',
            index=models.Index(fields=['tracking_number'], name='logistics_b_trackin_501aa6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='b2bshipmentbox',
            unique_together={('shipment', 'box_number')},
        ),
        migrations.AlterUniqueTogether(
            name='b2bboxitem',
            unique_together={('box', 'order_item')},
        ),
        migrations.AlterUniqueTogether(
            name='b2bshipmentitem',
            unique_together={('shipment', 'order_item')},
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['employee_id'], name='logistics_d_employe_7ec745_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['license_number'], name='logistics_d_license_a13fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_active', 'user'], name='logistics_d_is_acti_340127_idx'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['driver', '-recorded_at'], name='logistics_d_driver__3d7919_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentbox',
            index=models.Index(fields=['shipment', 'box_number'], name='logistics_s_shipmen_a292d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentbox',
            unique_together={('shipment', 'box_number')},
        ),
        migrations.AddIndex(
            model_name='boxitem',
            index=models.Index(fields=['box', 'order_item'], name='logistics_b_box_id_c2b48d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentitem',
            unique_together={('shipment', 'order_item')},
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate_number'], name='logistics_v_plate_n_0007a6_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['driver', 'is_active'], name='logistics_v_driver__657861_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active'], name='logistics_v_is_acti_aafa7a_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='logistics_w_code_89ed3f_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active', 'name'], name='logistics_w_is_acti_88f3be_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['logistic_office', 'is_active'], name='logistics_w_logisti_f25399_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='logistics_s_trackin_500f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', '-created_at'], name='logistics_s_status_cb8ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['driver', 'status'], name='logistics_s_driver__c25f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['warehouse', 'status'], name='logistics_s_warehou_7de8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order'], name='logistics_s_order_i_4704a4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['-collect_time'], name='logistics_s_collect_d7ccdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shipment',
            unique_together={('order', 'shipment_number')},
        ),
        migrations.AddIndex(
            model_name='warehouseshipmentnotification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='logistics_w_recipie_779723_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseshipmentnotification',
            index=models.Index(fields=['order', '-created_at'], name='logistics_w_order_i_f29f0f_idx'),
        ),
    ]
