# Generated by Django 5.2.4 on 2025-07-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_shipment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipping_cost',
        ),
    ]
