# Generated by Django 5.2.10 on 2026-01-30 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
        ('orders', '0003_alter_shippingaddress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsAgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='logistics_chat/%Y/%m/%d/')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_messages', to='orders.order')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_logistics_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logistics Agent Message',
                'verbose_name_plural': 'Logistics Agent Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLogisticsAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('working', 'Working on Order'), ('paused', 'Paused'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_working_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='Logistics staff/agent assigned to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_agent_assignment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Logistics Agent',
                'verbose_name_plural': 'Order Logistics Agents',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
