# Generated by Django 5.2.4 on 2025-07-16 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_remove_shipment_shipping_cost'),
        ('orders', '0014_orderitem_shipped_to_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.PositiveIntegerField()),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('label', models.ImageField(blank=True, null=True, upload_to='box_labels/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='logistics.shipment')),
            ],
            options={
                'ordering': ['box_number'],
                'unique_together': {('shipment', 'box_number')},
            },
        ),
        migrations.CreateModel(
            name='BoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.shipmentbox')),
            ],
        ),
    ]
