# Generated by Django 5.2.10 on 2026-02-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_warehousereceipt_trackingevent_warehousereceiptitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousereceipt',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='warehousereceipt',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='warehousereceipt',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='warehousereceiptitem',
            name='receipt',
        ),
        migrations.AlterUniqueTogether(
            name='warehousereceiptitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='warehousereceiptitem',
            name='shipment_item',
        ),
        migrations.DeleteModel(
            name='TrackingEvent',
        ),
        migrations.DeleteModel(
            name='WarehouseReceipt',
        ),
        migrations.DeleteModel(
            name='WarehouseReceiptItem',
        ),
    ]
