# Generated by Django 5.2.4 on 2025-07-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_shipmentbox_boxitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='verification_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verification_photos/'),
        ),
    ]
