# Generated by Django 5.2.10 on 2026-02-01 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_remove_warehousereceipt_received_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseReceiptOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(blank=True, db_index=True, help_text='Unique code for scanning and verifying receipt (WRH-XXXXXXXX)', max_length=20, null=True, unique=True, verbose_name='Verification Code')),
                ('status', models.CharField(choices=[('pending', 'Pending Receipt'), ('in_progress', 'Receipt In Progress'), ('received', 'Fully Received'), ('partial', 'Partially Received'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Receipt Status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Received At')),
                ('expected_arrival', models.DateTimeField(blank=True, help_text='When shipment is expected to arrive at warehouse', null=True, verbose_name='Expected Arrival')),
                ('has_issues', models.BooleanField(default=False, verbose_name='Has Issues')),
                ('issue_description', models.TextField(blank=True, verbose_name='Issue Description')),
                ('receiving_location', models.CharField(blank=True, help_text='Specific location/dock within warehouse', max_length=100, verbose_name='Receiving Location')),
                ('store_notified', models.BooleanField(default=False, verbose_name='Store Notified')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Notification Sent At')),
                ('notes', models.TextField(blank=True, verbose_name='Receipt Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_receipts_received', to=settings.AUTH_USER_MODEL, verbose_name='Received By')),
                ('shipment', models.ForeignKey(help_text='The shipment being received at warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_receipts', to='logistics.shipment')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='logistics.warehouse', verbose_name='Receiving Warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Receipt',
                'verbose_name_plural': 'Warehouse Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEventOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('shipment_created', 'Shipment Created'), ('shipped_to_warehouse', 'Shipped to Warehouse'), ('arrived_warehouse', 'Arrived at Warehouse'), ('scanned', 'Code Scanned'), ('receiving_started', 'Receiving Started'), ('item_verified', 'Item Verified'), ('receipt_completed', 'Receipt Completed'), ('issue_reported', 'Issue Reported'), ('status_changed', 'Status Changed')], db_index=True, max_length=30, verbose_name='Event Type')),
                ('tracking_code', models.CharField(db_index=True, help_text='Shipment tracking number or receipt verification code', max_length=50, verbose_name='Tracking Code')),
                ('location', models.CharField(blank=True, help_text='Where the event occurred', max_length=200, verbose_name='Location')),
                ('notes', models.TextField(blank=True, verbose_name='Event Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data', verbose_name='Event Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='logistics.shipment', verbose_name='Shipment')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='logistics.warehousereceiptorder', verbose_name='Warehouse Receipt')),
            ],
            options={
                'verbose_name': 'Tracking Event',
                'verbose_name_plural': 'Tracking Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseReceiptOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField(help_text='Quantity expected from shipment', verbose_name='Expected Quantity')),
                ('received_quantity', models.PositiveIntegerField(default=0, help_text='Actual quantity received', verbose_name='Received Quantity')),
                ('condition', models.CharField(choices=[('good', 'Good Condition'), ('damaged', 'Damaged'), ('missing', 'Missing'), ('incorrect', 'Incorrect Item')], default='good', max_length=20, verbose_name='Item Condition')),
                ('notes', models.TextField(blank=True, verbose_name='Item Notes')),
                ('photo', models.ImageField(blank=True, help_text='Photo of received item (especially for issues)', null=True, upload_to='warehouse/receipt_items/%Y/%m/%d/', verbose_name='Item Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.warehousereceiptorder', verbose_name='Warehouse Receipt')),
                ('shipment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_receipt_items', to='logistics.shipmentitem', verbose_name='Shipment Item')),
            ],
            options={
                'verbose_name': 'Warehouse Receipt Item',
                'verbose_name_plural': 'Warehouse Receipt Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='warehousereceiptorder',
            index=models.Index(fields=['verification_code'], name='logistics_w_verific_9f89d4_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousereceiptorder',
            index=models.Index(fields=['status'], name='logistics_w_status_113077_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousereceiptorder',
            index=models.Index(fields=['shipment'], name='logistics_w_shipmen_1d5ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousereceiptorder',
            index=models.Index(fields=['warehouse'], name='logistics_w_warehou_6ac055_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousereceiptorder',
            index=models.Index(fields=['-created_at'], name='logistics_w_created_81764e_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingeventorder',
            index=models.Index(fields=['tracking_code'], name='logistics_t_trackin_064bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingeventorder',
            index=models.Index(fields=['event_type'], name='logistics_t_event_t_aeaa74_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingeventorder',
            index=models.Index(fields=['-created_at'], name='logistics_t_created_5f13e5_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingeventorder',
            index=models.Index(fields=['shipment', '-created_at'], name='logistics_t_shipmen_7ddede_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingeventorder',
            index=models.Index(fields=['receipt', '-created_at'], name='logistics_t_receipt_7992b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousereceiptorderitem',
            unique_together={('receipt', 'shipment_item')},
        ),
    ]
