# Generated by Django 5.2.9 on 2026-01-02 19:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_alter_shipment_status'),
        ('orders', '0024_chatmessage_image_alter_chatmessage_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxitem',
            options={'ordering': ['box', 'order_item'], 'verbose_name': 'Box Item', 'verbose_name_plural': 'Box Items'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.AlterModelOptions(
            name='logisticoffice',
            options={'ordering': ['name'], 'verbose_name': 'Logistic Office', 'verbose_name_plural': 'Logistic Offices'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shipment', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterModelOptions(
            name='shipmentbox',
            options={'ordering': ['shipment', 'box_number'], 'verbose_name': 'Shipment Box', 'verbose_name_plural': 'Shipment Boxes'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['plate_number'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AddField(
            model_name='boxitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this item in the box', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='boxitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='date_hired',
            field=models.DateField(default=django.utils.timezone.now, help_text='Employment start date', verbose_name='Date Hired'),
        ),
        migrations.AddField(
            model_name='driver',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was deactivated', null=True, verbose_name='Deactivated At'),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='driver',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique employee identifier', max_length=20, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True, help_text="Expiration date of driver's license", null=True, verbose_name='License Expiry Date'),
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='logisticoffice',
            name='code',
            field=models.CharField(blank=True, help_text='Unique identifier code (auto-generated if empty)', max_length=20, unique=True, verbose_name='Office Code'),
        ),
        migrations.AddField(
            model_name='logisticoffice',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email for the office', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='logisticoffice',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='logisticoffice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logisticoffice',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was deactivated', null=True, verbose_name='Deactivated At'),
        ),
        migrations.AddField(
            model_name='logisticoffice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='logisticoffice',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Office timezone for scheduling operations', max_length=50, verbose_name='Timezone'),
        ),
        migrations.AddField(
            model_name='logisticoffice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='actual_dropoff_time',
            field=models.DateTimeField(blank=True, help_text='Actual delivery completion time', null=True, verbose_name='Actual Dropoff Time'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the delivery', verbose_name='Delivery Notes'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Shipping Cost'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special handling or delivery instructions', verbose_name='Special Instructions'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique tracking identifier', max_length=50, unique=True, verbose_name='Tracking Number'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='shipmentbox',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Format: LxWxH in cm', max_length=50, verbose_name='Dimensions'),
        ),
        migrations.AddField(
            model_name='shipmentbox',
            name='qr_data',
            field=models.TextField(blank=True, help_text='Data encoded in the QR code', verbose_name='QR Data'),
        ),
        migrations.AddField(
            model_name='shipmentbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_cubic_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum volume capacity in cubic meters', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capacity (m³)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was deactivated', null=True, verbose_name='Deactivated At'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'Compressed Natural Gas')], default='gasoline', max_length=20, verbose_name='Fuel Type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_maintenance',
            field=models.DateField(blank=True, help_text='Date of last maintenance service', null=True, verbose_name='Last Maintenance'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_maintenance',
            field=models.DateField(blank=True, help_text='Scheduled date for next maintenance', null=True, verbose_name='Next Maintenance'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, unique=True, verbose_name='VIN'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Manufacturing year', null=True, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='capacity_cubic_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total storage capacity in cubic meters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capacity (m³)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, help_text='Unique warehouse identifier', max_length=20, unique=True, verbose_name='Warehouse Code'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='current_utilization',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current warehouse utilization percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Current Utilization (%)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was deactivated', null=True, verbose_name='Deactivated At'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indicates if the record is active', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='logistic_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='logistics.logisticoffice', verbose_name='Logistic Office'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate', max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Warehouse Manager'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='boxitem',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.shipmentbox', verbose_name='Box'),
        ),
        migrations.AlterField(
            model_name='boxitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_items', to='orders.orderitem', verbose_name='Order Item'),
        ),
        migrations.AlterField(
            model_name='boxitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Number of units packed in this box', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(help_text="Driver's license number", max_length=50, unique=True, verbose_name='License Number'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='logisticoffice',
            name='location',
            field=models.CharField(help_text='Physical address or location description', max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='logisticoffice',
            name='name',
            field=models.CharField(help_text='Official name of the logistics office', max_length=100, verbose_name='Office Name'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='collect_time',
            field=models.DateTimeField(help_text='Scheduled time for package collection', verbose_name='Collection Time'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='container_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('metal', 'Metal'), ('composite', 'Composite')], default='paper', max_length=20, verbose_name='Container Type'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.driver', verbose_name='Assigned Driver'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='estimated_dropoff_time',
            field=models.DateTimeField(help_text='Estimated delivery time', verbose_name='Estimated Dropoff Time'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='logistic_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.logisticoffice', verbose_name='Logistic Office'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='material_type',
            field=models.CharField(choices=[('fragile', 'Fragile'), ('flammable', 'Flammable'), ('chemical', 'Dangerous Chemical'), ('perishable', 'Perishable'), ('standard', 'Standard')], db_index=True, default='standard', max_length=20, verbose_name='Material Type'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='packing_type',
            field=models.CharField(choices=[('paper_box', 'Paper Box'), ('metal_box', 'Metal Box'), ('plastic_box', 'Plastic Box'), ('wooden_crate', 'Wooden Crate'), ('envelope', 'Envelope')], default='paper_box', max_length=20, verbose_name='Packing Type'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('express', 'Express'), ('normal', 'Normal'), ('economic', 'Economic'), ('free', 'Free'), ('same_day', 'Same Day')], db_index=True, default='normal', max_length=20, verbose_name='Shipment Type'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.shippingaddress', verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='size_cubic_meters',
            field=models.DecimalField(decimal_places=3, help_text='Total shipment volume in cubic meters', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Size (m³)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.vehicle', verbose_name='Assigned Vehicle'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='verification_photo',
            field=models.ImageField(blank=True, help_text='Photo proof of delivery', null=True, upload_to='shipments/verification/%Y/%m/%d/', verbose_name='Verification Photo'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, help_text='Total shipment weight in kilograms', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='shipmentbox',
            name='box_number',
            field=models.PositiveIntegerField(help_text='Sequential number within the shipment', verbose_name='Box Number'),
        ),
        migrations.AlterField(
            model_name='shipmentbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='shipmentbox',
            name='label',
            field=models.ImageField(blank=True, help_text='QR code label for the box', null=True, upload_to='shipments/box_labels/%Y/%m/%d/', verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='shipmentbox',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='logistics.shipment', verbose_name='Shipment'),
        ),
        migrations.AlterField(
            model_name='shipmentbox',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_kg',
            field=models.DecimalField(decimal_places=2, help_text='Maximum weight capacity in kilograms', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capacity (kg)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='logistics.driver', verbose_name='Assigned Driver'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(help_text='Vehicle make and model', max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(help_text='Vehicle license plate number', max_length=20, unique=True, verbose_name='Plate Number'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(help_text='Complete physical address of the warehouse', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(help_text='Name of the warehouse facility', max_length=100, verbose_name='Warehouse Name'),
        ),
        migrations.AddIndex(
            model_name='boxitem',
            index=models.Index(fields=['box', 'order_item'], name='logistics_b_box_id_c2b48d_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['employee_id'], name='logistics_d_employe_7ec745_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['license_number'], name='logistics_d_license_a13fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_active', 'user'], name='logistics_d_is_acti_340127_idx'),
        ),
        migrations.AddIndex(
            model_name='logisticoffice',
            index=models.Index(fields=['code'], name='logistics_l_code_98a7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='logisticoffice',
            index=models.Index(fields=['is_active', 'name'], name='logistics_l_is_acti_e744f0_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='logistics_s_trackin_500f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', '-created_at'], name='logistics_s_status_cb8ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['driver', 'status'], name='logistics_s_driver__c25f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['warehouse', 'status'], name='logistics_s_warehou_7de8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order'], name='logistics_s_order_i_4704a4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['-collect_time'], name='logistics_s_collect_d7ccdd_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentbox',
            index=models.Index(fields=['shipment', 'box_number'], name='logistics_s_shipmen_a292d3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate_number'], name='logistics_v_plate_n_0007a6_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['driver', 'is_active'], name='logistics_v_driver__657861_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active'], name='logistics_v_is_acti_aafa7a_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='logistics_w_code_89ed3f_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active', 'name'], name='logistics_w_is_acti_88f3be_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['logistic_office', 'is_active'], name='logistics_w_logisti_f25399_idx'),
        ),
    ]
