# Generated by Django 5.2.9 on 2026-01-04 02:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_boxitem_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('speed_mps', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='logistics.driver')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['driver', '-recorded_at'], name='logistics_d_driver__3d7919_idx')],
            },
        ),
    ]
