# Generated by Django 5.2.9 on 2026-01-08 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_driverlocation'),
        ('orders', '0026_shippingaddress_latitude_shippingaddress_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_number',
            field=models.PositiveIntegerField(default=1, help_text="Sequential number for this order's shipments"),
        ),
        migrations.AlterUniqueTogether(
            name='shipment',
            unique_together={('order', 'shipment_number')},
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='orders.orderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='logistics.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Item',
                'verbose_name_plural': 'Shipment Items',
                'ordering': ['added_at'],
                'unique_together': {('shipment', 'order_item')},
            },
        ),
    ]
