# Generated by Django 5.2.9 on 2026-01-08 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_shipment_shipment_number_and_more'),
        ('orders', '0027_orderitem_current_shipment_and_more'),
        ('stores', '0023_store_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseShipmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('item_shipped', 'Item Shipped to Warehouse'), ('all_items_shipped', 'All Items Shipped'), ('shipment_created', 'Shipment Created')], default='item_shipped', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('items_count', models.PositiveIntegerField(default=1)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_notifications', to='orders.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_notifications', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_notifications', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='logistics_w_recipie_779723_idx'), models.Index(fields=['order', '-created_at'], name='logistics_w_order_i_f29f0f_idx')],
            },
        ),
    ]
