# Generated by Django 5.2.9 on 2026-01-10 10:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_warehouseshipmentnotification'),
        ('stores', '0023_store_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cubic_m', models.DecimalField(blank=True, decimal_places=3, help_text='Cubic meters (m³)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('total_boxes', models.PositiveIntegerField(default=0)),
                ('material_type', models.CharField(choices=[('standard', 'Standard'), ('fragile', 'Fragile'), ('flammable', 'Flammable'), ('chemical', 'Dangerous Chemical'), ('perishable', 'Perishable')], default='standard', max_length=20)),
                ('material_class', models.CharField(blank=True, help_text='Optional material class (e.g. Class 3 Flammable Liquids)', max_length=80)),
                ('shipment_mode', models.CharField(choices=[('easy_move', 'Easy Move (Normal)'), ('cargo', 'Cargo'), ('air_freight', 'Air Freight')], default='easy_move', max_length=20)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('eta_text', models.CharField(blank=True, help_text='Estimated delivery time, e.g. 3-5 days', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_shipment', to='stores.b2border')),
                ('shipping_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_shipment', to='stores.b2bshippingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='B2BShipmentBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('dimensions', models.CharField(blank=True, help_text='LxWxH in cm (optional)', max_length=50)),
                ('label', models.ImageField(blank=True, null=True, upload_to='b2b_shipments/box_labels/%Y/%m/%d/')),
                ('qr_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='logistics.b2bshipment')),
            ],
            options={
                'ordering': ['shipment', 'box_number'],
                'unique_together': {('shipment', 'box_number')},
            },
        ),
        migrations.CreateModel(
            name='B2BBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_box_items', to='stores.b2borderitem')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.b2bshipmentbox')),
            ],
            options={
                'unique_together': {('box', 'order_item')},
            },
        ),
        migrations.CreateModel(
            name='B2BShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_shipment_items', to='stores.b2borderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='logistics.b2bshipment')),
            ],
            options={
                'unique_together': {('shipment', 'order_item')},
            },
        ),
    ]
