# Generated by Django 5.2.10 on 2026-01-10 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_b2bshipment_b2bshipmentbox_b2bboxitem_and_more'),
        ('stores', '0023_store_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b2bshipment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when shipment was locked', null=True),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='User who locked the shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - Editable'), ('locked', 'Locked - Labels Generated')], default='draft', help_text='Draft = editable, Locked = read-only after labels generated', max_length=20),
        ),
        migrations.AddIndex(
            model_name='b2bshipment',
            index=models.Index(fields=['status', 'created_at'], name='logistics_b_status_288d55_idx'),
        ),
        migrations.AddIndex(
            model_name='b2bshipment',
            index=models.Index(fields=['tracking_number'], name='logistics_b_trackin_501aa6_idx'),
        ),
    ]
