# Generated by Django 5.2.10 on 2026-01-10 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_alter_b2bshipment_options_b2bshipment_locked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bshipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when shipment was marked as delivered', null=True),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='delivered_by',
            field=models.ForeignKey(blank=True, help_text='User who marked shipment as delivered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Notes about the delivery (signature, condition, etc.)'),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='delivery_proof',
            field=models.ImageField(blank=True, help_text='Photo proof of delivery (optional)', null=True, upload_to='shipment_delivery_proofs/'),
        ),
        migrations.AlterField(
            model_name='b2bshipment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - Editable'), ('locked', 'Locked - Labels Generated'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='draft', help_text='Draft = editable, Locked = read-only after labels generated, In Transit = shipped, Delivered = completed', max_length=20),
        ),
    ]
