# Generated by Django 5.2.10 on 2026-01-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_shipment_created_by'),
        ('supply_chain', '0003_shippingcompany_supported_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bshipment',
            name='company_config',
            field=models.ForeignKey(blank=True, help_text='Selected shipping company configuration based on origin + mode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_shipments', to='supply_chain.shippingcompanycountry'),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='shipping_company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
