# Generated by Django 5.2.9 on 2026-01-05 08:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0044_alter_product_options_product_b2b_min_quantity_and_more'),
        ('stock', '0002_alter_stock_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g., Net 30', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['product', 'warehouse']},
        ),
        migrations.AddField(
            model_name='stock',
            name='last_counted',
            field=models.DateTimeField(blank=True, help_text='Last physical count date', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10, help_text='Minimum quantity before reorder'),
        ),
        migrations.AddField(
            model_name='stock',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=50, help_text='Quantity to reorder'),
        ),
        migrations.AddField(
            model_name='stock',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('SENT', 'Sent to Supplier'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Fully Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='stock.supplier')),
            ],
            options={
                'ordering': ['-order_date', '-po_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock Level'), ('OUT_OF_STOCK', 'Out of Stock'), ('OVERSTOCK', 'Overstock'), ('EXPIRING_SOON', 'Expiring Soon'), ('NEGATIVE_STOCK', 'Negative Stock Error')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='ACTIVE', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stock.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField()),
                ('counted_quantity', models.PositiveIntegerField()),
                ('variance', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stockcount')),
            ],
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order_reference', models.CharField(max_length=100)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Reservation expiry time')),
                ('is_active', models.BooleanField(default=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stock.stock')),
            ],
            options={
                'ordering': ['-reserved_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_warehouses_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase/Receiving'), ('SALE', 'Sale/Dispatch'), ('RETURN_IN', 'Customer Return'), ('RETURN_OUT', 'Return to Supplier'), ('TRANSFER', 'Warehouse Transfer'), ('ADJUSTMENT', 'Stock Adjustment'), ('DAMAGE', 'Damaged Goods'), ('LOSS', 'Lost/Stolen'), ('PRODUCTION', 'Production Usage'), ('ASSEMBLY', 'Assembly/Manufacturing')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for increase, negative for decrease')),
                ('reference_number', models.CharField(blank=True, help_text='PO, SO, or other reference', max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='marketplace.product')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='stock.warehouse')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockcount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='stock.warehouse'),
        ),
        migrations.CreateModel(
            name='StockAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_stock', models.IntegerField(default=0)),
                ('closing_stock', models.IntegerField(default=0)),
                ('total_received', models.IntegerField(default=0)),
                ('total_sold', models.IntegerField(default=0)),
                ('total_adjusted', models.IntegerField(default=0)),
                ('total_purchase_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sales_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('average_unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('turnover_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Daily turnover rate', max_digits=5)),
                ('days_of_stock', models.IntegerField(default=0, help_text='Days until stockout at current rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='marketplace.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='stock.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Stock Analytics',
                'ordering': ['-date', 'product', 'warehouse'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='stock.warehouse'),
        ),
        migrations.CreateModel(
            name='BatchTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier_reference', models.CharField(blank=True, max_length=100)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='marketplace.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stock.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Batch Tracking',
                'ordering': ['expiry_date', 'batch_number'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='stock.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'warehouse'], name='stock_stock_product_e918e5_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['quantity'], name='stock_stock_quantit_ffb26c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together={('purchase_order', 'product')},
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['status', '-created_at'], name='stock_stock_status_c383f2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['alert_type', 'status'], name='stock_stock_alert_t_29900b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcountitem',
            unique_together={('stock_count', 'product')},
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['order_reference'], name='stock_stock_order_r_65953d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['is_active', 'expires_at'], name='stock_stock_is_acti_aae825_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-created_at'], name='stock_stock_product_d71e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', '-created_at'], name='stock_stock_warehou_662f23_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='stock_stock_movemen_cbf66e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_number'], name='stock_stock_referen_07e55d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockanalytics',
            index=models.Index(fields=['date', 'product'], name='stock_stock_date_6e30c4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockanalytics',
            index=models.Index(fields=['date', 'warehouse'], name='stock_stock_date_bdefbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockanalytics',
            unique_together={('product', 'warehouse', 'date')},
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='stock_purch_po_numb_76bea9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', '-order_date'], name='stock_purch_status_614e92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batchtracking',
            unique_together={('product', 'batch_number', 'warehouse')},
        ),
    ]
