# Generated by Django 5.2.9 on 2026-01-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_purchaseorder_warehouse_alter_stock_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='capacity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
