# Generated by Django 5.2.10 on 2026-01-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_warehouse_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Maximum storage capacity in units (0 = unlimited)'),
        ),
    ]
