# Generated by Django 5.2.9 on 2026-01-05 08:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0008_driverlocation'),
        ('marketplace', '0044_alter_product_options_product_b2b_min_quantity_and_more'),
        ('orders', '0026_shippingaddress_latitude_shippingaddress_longitude_and_more'),
        ('stock', '0003_supplier_alter_stock_options_stock_last_counted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreToLogisticsTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(help_text='Unique transfer identifier', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Pickup'), ('IN_TRANSIT', 'In Transit to Logistics'), ('RECEIVED', 'Received at Logistics'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_scheduled', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60, help_text='Estimated transfer duration in minutes')),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Actual transfer duration in minutes', null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transfers', to='logistics.driver')),
                ('logistics_warehouse', models.ForeignKey(help_text='EasyMarket logistics warehouse (destination)', on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transfers', to='logistics.warehouse')),
                ('order', models.ForeignKey(blank=True, help_text='Associated customer order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_transfers', to='orders.order')),
                ('picked_up_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_transfers', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('store_warehouse', models.ForeignKey(help_text='Store warehouse (source)', on_delete=django.db.models.deletion.PROTECT, related_name='outbound_transfers', to='stock.warehouse')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transfers', to='logistics.vehicle')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'In Queue'), ('PICKING', 'Being Picked'), ('PACKING', 'Being Packed'), ('READY', 'Ready for Shipment'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('NORMAL', 'Normal Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('picking_started_at', models.DateTimeField(blank=True, null=True)),
                ('packing_started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_pick_time_minutes', models.PositiveIntegerField(default=15)),
                ('actual_pick_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_pack_time_minutes', models.PositiveIntegerField(default=10)),
                ('actual_pack_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('logistics_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_queue', to='logistics.warehouse')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_queue', to='orders.order')),
                ('packer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_orders', to=settings.AUTH_USER_MODEL)),
                ('picker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_orders', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillment_entries', to='logistics.shipment')),
                ('transfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillment_entries', to='supply_chain.storetologisticstransfer')),
            ],
            options={
                'ordering': ['-priority', 'queued_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('transferred', models.BooleanField(default=False, help_text='Has been transferred to logistics warehouse')),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('condition_notes', models.TextField(blank=True, help_text='Notes about product condition during transfer')),
                ('damaged', models.BooleanField(default=False)),
                ('damage_notes', models.TextField(blank=True)),
                ('order_item', models.ForeignKey(blank=True, help_text='Corresponding order item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.product')),
                ('stock_reservation', models.ForeignKey(blank=True, help_text='Stock reservation at store warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stockreservation')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supply_chain.storetologisticstransfer')),
            ],
            options={
                'ordering': ['transfer', 'product'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLinkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='Is this the primary logistics warehouse for this store?')),
                ('is_active', models.BooleanField(default=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance between warehouses', max_digits=8, null=True)),
                ('estimated_transfer_time_minutes', models.PositiveIntegerField(default=60, help_text='Estimated transfer time')),
                ('max_daily_transfers', models.PositiveIntegerField(default=10, help_text='Maximum transfers per day from this store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logistics_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_linkages', to='logistics.warehouse')),
                ('store_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_linkages', to='stock.warehouse')),
            ],
            options={
                'ordering': ['store_warehouse', '-is_primary'],
            },
        ),
        migrations.AddIndex(
            model_name='storetologisticstransfer',
            index=models.Index(fields=['transfer_number'], name='supply_chai_transfe_b7163b_idx'),
        ),
        migrations.AddIndex(
            model_name='storetologisticstransfer',
            index=models.Index(fields=['status', '-requested_at'], name='supply_chai_status_c75992_idx'),
        ),
        migrations.AddIndex(
            model_name='storetologisticstransfer',
            index=models.Index(fields=['order'], name='supply_chai_order_i_5568a3_idx'),
        ),
        migrations.AddIndex(
            model_name='storetologisticstransfer',
            index=models.Index(fields=['store_warehouse', 'status'], name='supply_chai_store_w_638489_idx'),
        ),
        migrations.AddIndex(
            model_name='storetologisticstransfer',
            index=models.Index(fields=['logistics_warehouse', 'status'], name='supply_chai_logisti_32c289_idx'),
        ),
        migrations.AddIndex(
            model_name='fulfillmentqueue',
            index=models.Index(fields=['status', '-priority', 'queued_at'], name='supply_chai_status_5837ee_idx'),
        ),
        migrations.AddIndex(
            model_name='fulfillmentqueue',
            index=models.Index(fields=['logistics_warehouse', 'status'], name='supply_chai_logisti_044750_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transferitem',
            unique_together={('transfer', 'product')},
        ),
        migrations.AddIndex(
            model_name='warehouselinkage',
            index=models.Index(fields=['store_warehouse', 'is_primary', 'is_active'], name='supply_chai_store_w_acae61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouselinkage',
            unique_together={('store_warehouse', 'logistics_warehouse')},
        ),
    ]
