# Generated by Django 5.2.10 on 2026-01-11 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_shipment_created_by'),
        ('orders', '0027_orderitem_current_shipment_and_more'),
        ('stock', '0005_warehouse_capacity'),
        ('stores', '0023_store_warehouse'),
        ('supply_chain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('package_count', models.IntegerField(default=1)),
                ('dimensions_cm', models.CharField(blank=True, help_text='LxWxH in cm (e.g., 50x40x30)', max_length=50)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customs_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('carrier_tracking_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('CUSTOMS', 'In Customs'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETURNED', 'Returned')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('commercial_invoice', models.FileField(blank=True, null=True, upload_to='shipments/invoices/')),
                ('packing_list', models.FileField(blank=True, null=True, upload_to='shipments/packing/')),
                ('customs_declaration', models.FileField(blank=True, null=True, upload_to='shipments/customs/')),
                ('notes', models.TextField(blank=True)),
                ('customs_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CountryShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_customs', models.BooleanField(default=False)),
                ('estimated_delivery_days', models.IntegerField(default=7)),
                ('max_package_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('restricted_items', models.TextField(blank=True, help_text='Comma-separated list of restricted product categories')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Country Shipping Configurations',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shipping/logos/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True)),
                ('has_api_integration', models.BooleanField(default=False)),
                ('api_endpoint', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('supports_tracking', models.BooleanField(default=True)),
                ('supports_insurance', models.BooleanField(default=False)),
                ('supports_cod', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCompanyCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Base shipping rate in USD', max_digits=10)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, help_text='Additional rate per kg', max_digits=10)),
                ('service_level', models.CharField(choices=[('STANDARD', 'Standard'), ('EXPRESS', 'Express'), ('ECONOMY', 'Economy')], default='STANDARD', max_length=50)),
                ('estimated_days', models.IntegerField(default=7)),
                ('priority', models.IntegerField(default=1, help_text='Lower number = higher priority (shown first)')),
                ('is_active', models.BooleanField(default=True)),
                ('min_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'ordering': ['country', 'priority'],
            },
        ),
        migrations.AlterModelOptions(
            name='fulfillmentqueue',
            options={'ordering': ['priority', 'queued_at']},
        ),
        migrations.AlterModelOptions(
            name='transferitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouselinkage',
            options={'ordering': ['store_warehouse', 'priority']},
        ),
        migrations.RemoveIndex(
            model_name='fulfillmentqueue',
            name='supply_chai_status_5837ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='fulfillmentqueue',
            name='supply_chai_logisti_044750_idx',
        ),
        migrations.RemoveIndex(
            model_name='storetologisticstransfer',
            name='supply_chai_transfe_b7163b_idx',
        ),
        migrations.RemoveIndex(
            model_name='storetologisticstransfer',
            name='supply_chai_status_c75992_idx',
        ),
        migrations.RemoveIndex(
            model_name='storetologisticstransfer',
            name='supply_chai_order_i_5568a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='storetologisticstransfer',
            name='supply_chai_store_w_638489_idx',
        ),
        migrations.RemoveIndex(
            model_name='storetologisticstransfer',
            name='supply_chai_logisti_32c289_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouselinkage',
            name='supply_chai_store_w_acae61_idx',
        ),
        migrations.RenameField(
            model_name='fulfillmentqueue',
            old_name='packer',
            new_name='packed_by',
        ),
        migrations.RenameField(
            model_name='fulfillmentqueue',
            old_name='ready_at',
            new_name='packing_completed_at',
        ),
        migrations.RenameField(
            model_name='fulfillmentqueue',
            old_name='picker',
            new_name='picked_by',
        ),
        migrations.AlterUniqueTogether(
            name='transferitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fulfillmentqueue',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='storetologisticstransfer',
            name='estimated_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='storetologisticstransfer',
            name='pickup_scheduled',
        ),
        migrations.RemoveField(
            model_name='storetologisticstransfer',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='fulfillmentqueue',
            name='picking_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfillmentqueue',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouselinkage',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehouselinkage',
            name='operating_hours_end',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='warehouselinkage',
            name='operating_hours_start',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='warehouselinkage',
            name='priority',
            field=models.IntegerField(default=1, help_text='Lower number = higher priority'),
        ),
        migrations.AlterField(
            model_name='fulfillmentqueue',
            name='actual_pack_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fulfillmentqueue',
            name='actual_pick_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fulfillmentqueue',
            name='estimated_pack_time_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='fulfillmentqueue',
            name='estimated_pick_time_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='fulfillmentqueue',
            name='priority',
            field=models.CharField(choices=[('URGENT', 'Urgent'), ('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='fulfillmentqueue',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'In Queue'), ('PICKING', 'Being Picked'), ('PACKING', 'Being Packed'), ('READY', 'Ready to Ship'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20),
        ),
        migrations.AlterField(
            model_name='fulfillmentqueue',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chain.storetologisticstransfer'),
        ),
        migrations.AlterField(
            model_name='storetologisticstransfer',
            name='actual_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storetologisticstransfer',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.driver'),
        ),
        migrations.AlterField(
            model_name='storetologisticstransfer',
            name='logistics_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transfers', to='logistics.warehouse'),
        ),
        migrations.AlterField(
            model_name='storetologisticstransfer',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_transfers', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='storetologisticstransfer',
            name='picked_up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_up_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storetologisticstransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Pickup'), ('PICKED_UP', 'In Transit'), ('RECEIVED', 'Received at Logistics'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='storetologisticstransfer',
            name='store_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_transfers', to='stock.warehouse'),
        ),
        migrations.AlterField(
            model_name='storetologisticstransfer',
            name='transfer_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='storetologisticstransfer',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicle'),
        ),
        migrations.AlterField(
            model_name='transferitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='transferitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transferitem',
            name='stock_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stockreservation'),
        ),
        migrations.AlterField(
            model_name='warehouselinkage',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance between warehouses in km', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='warehouselinkage',
            name='estimated_transfer_time_minutes',
            field=models.IntegerField(default=60, help_text='Estimated time to transfer goods'),
        ),
        migrations.AlterField(
            model_name='warehouselinkage',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Primary logistics warehouse for this store'),
        ),
        migrations.AlterField(
            model_name='warehouselinkage',
            name='max_daily_transfers',
            field=models.IntegerField(default=10, help_text='Maximum number of daily transfers'),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='b2b_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='stores.b2border'),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='supply_chain.countryshippingconfig'),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='supply_chain.b2bshipment'),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='shipping_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='supply_chain.shippingcompany'),
        ),
        migrations.AddField(
            model_name='shippingcompanycountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_configs', to='supply_chain.countryshippingconfig'),
        ),
        migrations.AddField(
            model_name='shippingcompanycountry',
            name='shipping_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_configs', to='supply_chain.shippingcompany'),
        ),
        migrations.AddField(
            model_name='shippingcompany',
            name='countries',
            field=models.ManyToManyField(related_name='shipping_companies', through='supply_chain.ShippingCompanyCountry', to='supply_chain.countryshippingconfig'),
        ),
        migrations.AddField(
            model_name='b2bshipment',
            name='company_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='supply_chain.shippingcompanycountry'),
        ),
        migrations.RemoveField(
            model_name='transferitem',
            name='condition_notes',
        ),
        migrations.RemoveField(
            model_name='transferitem',
            name='damage_notes',
        ),
        migrations.RemoveField(
            model_name='transferitem',
            name='damaged',
        ),
        migrations.RemoveField(
            model_name='transferitem',
            name='transferred',
        ),
        migrations.RemoveField(
            model_name='transferitem',
            name='transferred_at',
        ),
        migrations.AlterUniqueTogether(
            name='shippingcompanycountry',
            unique_together={('shipping_company', 'country', 'service_level')},
        ),
    ]
