# Generated by Django 5.2.10 on 2026-01-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_b2bshipment_countryshippingconfig_shipmenttracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcompany',
            name='supported_modes',
            field=models.JSONField(blank=True, default=list, help_text="Example: ['easy_move', 'cargo', 'air_freight']. Leave empty = supports all."),
        ),
    ]
