# Generated by Django 5.2.10 on 2026-01-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0023_store_warehouse'),
        ('supply_chain', '0003_shippingcompany_supported_modes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storetologisticstransfer',
            options={},
        ),
        migrations.RemoveField(
            model_name='storetologisticstransfer',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='storetologisticstransfer',
            name='picked_up_at',
        ),
        migrations.RemoveField(
            model_name='storetologisticstransfer',
            name='picked_up_by',
        ),
        migrations.RemoveField(
            model_name='storetologisticstransfer',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='storetologisticstransfer',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='storetologisticstransfer',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='storetologisticstransfer',
            name='b2b_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_transfers', to='stores.b2border'),
        ),
        migrations.AlterField(
            model_name='storetologisticstransfer',
            name='actual_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Actual transfer duration in minutes', null=True),
        ),
    ]
