# Generated by Django 5.2.10 on 2026-01-11 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0004_add_shipping_fields_to_fulfillment_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfillmentqueue',
            name='shipped_by',
        ),
        migrations.AlterField(
            model_name='fulfillmentqueue',
            name='shipped_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
