# Generated by Django 5.2.10 on 2026-01-11 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_b2bshipment_company_config_and_more'),
        ('supply_chain', '0004_alter_storetologisticstransfer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storetologisticstransfer',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AddField(
            model_name='storetologisticstransfer',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='logistics.driver'),
        ),
        migrations.AddField(
            model_name='storetologisticstransfer',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storetologisticstransfer',
            name='picked_up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_up_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storetologisticstransfer',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storetologisticstransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storetologisticstransfer',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='logistics.vehicle'),
        ),
    ]
