# Generated by Django 5.2.10 on 2026-01-11 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_orderitem_current_shipment_and_more'),
        ('stores', '0023_store_warehouse'),
        ('supply_chain', '0005_alter_storetologisticstransfer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fulfillmentqueue',
            options={},
        ),
        migrations.RemoveField(
            model_name='fulfillmentqueue',
            name='shipped_at',
        ),
        migrations.RemoveField(
            model_name='fulfillmentqueue',
            name='shipped_by',
        ),
        migrations.AddField(
            model_name='fulfillmentqueue',
            name='b2b_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_queue', to='stores.b2border'),
        ),
        migrations.AlterField(
            model_name='fulfillmentqueue',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_queue', to='orders.order'),
        ),
    ]
