# Generated by Django 5.2.10 on 2026-01-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0005_remove_fulfillmentqueue_shipped_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fulfillmentqueue',
            options={'ordering': ['priority', 'queued_at'], 'verbose_name': 'Fulfillment Queue', 'verbose_name_plural': 'Fulfillment Queues'},
        ),
    ]
