version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: easy_market
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dazzling@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DEBUG: "1"
      DATABASE_URL: postgres://postgres:dazzling%40123@db:5432/easy_market
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1

  celery:
    build: .
    command: celery -A easymarket worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:dazzling%40123@db:5432/easy_market
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1

  celery-beat:
    build: .
    command: celery -A easymarket beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:dazzling%40123@db:5432/easy_market
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1

volumes:
  postgres_data:
  media_volume:
