services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: easy_market
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dazzling@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:dazzling%40123@db:5432/easy_market

volumes:
  postgres_data:
  media_volume:
