# Generated by Django 5.2.5 on 2025-12-16 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('marketplace', '0044_alter_product_options_product_b2b_min_quantity_and_more'),
        ('orders', '0024_chatmessage_image_alter_chatmessage_content_and_more'),
        ('stores', '0020_b2border_tracking_note_b2border_tracking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('returning_visitors', models.PositiveIntegerField(default=0)),
                ('add_to_cart', models.PositiveIntegerField(default=0)),
                ('checkout', models.PositiveIntegerField(default=0)),
                ('paid', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cart_abandonment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('event', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add To Cart'), ('remove_from_cart', 'Remove From Cart'), ('checkout', 'Checkout'), ('paid', 'Paid')], db_index=True, max_length=32)),
                ('path', models.CharField(blank=True, db_index=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'created_at'], name='analytics_a_event_304b34_idx'), models.Index(fields=['store', 'event', 'created_at'], name='analytics_a_store_i_4e7911_idx'), models.Index(fields=['product', 'event', 'created_at'], name='analytics_a_product_36eecc_idx'), models.Index(fields=['session_key', 'created_at'], name='analytics_a_session_b528aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('add_to_cart', models.PositiveIntegerField(default=0)),
                ('checkout', models.PositiveIntegerField(default=0)),
                ('paid', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'date'], name='analytics_s_store_i_c4a88b_idx')],
                'unique_together': {('date', 'store')},
            },
        ),
    ]
