# Generated by Django 5.2.5 on 2025-12-16 05:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticsdailysummary_analyticsevent_and_more'),
        ('stores', '0020_b2border_tracking_note_b2border_tracking_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedailysummary',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveIndex(
            model_name='storedailysummary',
            name='analytics_s_store_i_c4a88b_idx',
        ),
        migrations.RenameField(
            model_name='storedailysummary',
            old_name='product_views',
            new_name='page_views',
        ),
        migrations.AlterUniqueTogether(
            name='storedailysummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='storedailysummary',
            name='bounce_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='storedailysummary',
            name='cart_abandonment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='storedailysummary',
            name='returning_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storedailysummary',
            name='unique_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storedailysummary',
            name='view_product',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storedailysummary',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='storedailysummary',
            unique_together={('store', 'date')},
        ),
    ]
