# Generated by Django 5.2.9 on 2025-12-16 07:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_storedailysummary_options_and_more'),
        ('marketplace', '0044_alter_product_options_product_b2b_min_quantity_and_more'),
        ('orders', '0024_chatmessage_image_alter_chatmessage_content_and_more'),
        ('stores', '0020_b2border_tracking_note_b2border_tracking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsdailysummary',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Analytics Daily Summaries'},
        ),
        migrations.AlterModelOptions(
            name='analyticsevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storedailysummary',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Store Daily Summaries'},
        ),
        migrations.RemoveIndex(
            model_name='pageview',
            name='analytics_p_created_4c2b45_idx',
        ),
        migrations.RemoveIndex(
            model_name='pageview',
            name='analytics_p_path_3382b5_idx',
        ),
        migrations.AddField(
            model_name='storedailysummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedailysummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='marketplace.product'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='cartevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cartevent',
            name='event',
            field=models.CharField(choices=[('add', 'Add to Cart'), ('remove', 'Remove from Cart'), ('checkout', 'Checkout'), ('abandoned', 'Abandoned'), ('completed', 'Completed')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cartevent',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='path',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='visitsession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='visitsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'event', 'created_at'], name='analytics_a_user_id_d548c5_idx'),
        ),
        migrations.AddIndex(
            model_name='cartevent',
            index=models.Index(fields=['event', 'created_at'], name='analytics_c_event_0ea072_idx'),
        ),
        migrations.AddIndex(
            model_name='cartevent',
            index=models.Index(fields=['session_key', 'event'], name='analytics_c_session_a3f22b_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['created_at', 'session_key'], name='analytics_p_created_65f3df_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['path', 'created_at'], name='analytics_p_path_53ae0e_idx'),
        ),
        migrations.AddIndex(
            model_name='storedailysummary',
            index=models.Index(fields=['store', 'date'], name='analytics_s_store_i_c4a88b_idx'),
        ),
        migrations.AddIndex(
            model_name='storedailysummary',
            index=models.Index(fields=['date', 'revenue'], name='analytics_s_date_3ae7b5_idx'),
        ),
        migrations.AddIndex(
            model_name='visitsession',
            index=models.Index(fields=['user', 'started_at'], name='analytics_v_user_id_1746e2_idx'),
        ),
    ]
