# Generated by Django 5.2.4 on 2025-07-17 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0014_orderitem_shipped_to_warehouse'),
        ('stores', '0002_storeinventorytracking_storereturnsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialMetricsIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_commission_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_return_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Metrics Integration',
                'verbose_name_plural': 'Financial Metrics Integrations',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['-transaction_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='logisticsintegration',
            options={'verbose_name': 'Logistics Integration', 'verbose_name_plural': 'Logistics Integrations'},
        ),
        migrations.AlterModelOptions(
            name='storefinancialsummary',
            options={'ordering': ['-period_start'], 'verbose_name': 'Store Financial Summary', 'verbose_name_plural': 'Store Financial Summaries'},
        ),
        migrations.RenameField(
            model_name='logisticsintegration',
            old_name='total_orders',
            new_name='completed_return_pickups',
        ),
        migrations.RenameField(
            model_name='storefinancialsummary',
            old_name='total_commissions',
            new_name='commission_expenses',
        ),
        migrations.AlterUniqueTogether(
            name='logisticsintegration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='order_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='return_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='orders.return'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='logisticsintegration',
            name='average_processing_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='logisticsintegration',
            name='customer_satisfaction_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='logisticsintegration',
            name='on_time_delivery_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='logisticsintegration',
            name='pending_return_pickups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logisticsintegration',
            name='return_rate_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='logisticsintegration',
            name='total_return_shipments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefinancialsummary',
            name='commission_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storefinancialsummary',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storefinancialsummary',
            name='marketing_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storefinancialsummary',
            name='operational_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storefinancialsummary',
            name='profit_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='storefinancialsummary',
            name='return_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storefinancialsummary',
            name='shipping_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storefinancialsummary',
            name='shipping_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storefinancialsummary',
            name='total_returns_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='category',
            field=models.CharField(choices=[('sales', 'Sales Revenue'), ('commission', 'Commission Fees'), ('shipping', 'Shipping & Logistics'), ('returns', 'Returns & Refunds'), ('marketing', 'Marketing & Advertising'), ('operations', 'Operations'), ('platform', 'Platform Fees'), ('tax', 'Taxes'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='record_type',
            field=models.CharField(choices=[('revenue', 'Revenue'), ('expense', 'Expense'), ('refund', 'Refund'), ('commission', 'Commission'), ('return_cost', 'Return Processing Cost'), ('shipping_cost', 'Shipping Cost'), ('platform_fee', 'Platform Fee'), ('marketing', 'Marketing Expense'), ('operational', 'Operational Cost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='logisticsintegration',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_summary', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='storefinancialsummary',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summaries', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['store', 'transaction_date'], name='finance_fin_store_i_e902cf_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['record_type', 'transaction_date'], name='finance_fin_record__7e2525_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['store', 'category'], name='finance_fin_store_i_6ed1a1_idx'),
        ),
        migrations.AddField(
            model_name='financialmetricsintegration',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_metrics_integration', to='stores.store'),
        ),
        migrations.AddField(
            model_name='financialmetricsintegration',
            name='store_metrics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_integration', to='stores.storemetrics'),
        ),
        migrations.AlterUniqueTogether(
            name='financialmetricsintegration',
            unique_together={('store', 'date')},
        ),
    ]
