# Generated by Django 5.2.10 on 2026-02-01 15:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossroadDealConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_fee', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Fee for listing an item (for buyers who want to sell)', max_digits=10)),
                ('vetting_fee', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Fee for Easy Move to vet the product', max_digits=10)),
                ('pickup_base_fee', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Base fee for direct pickup', max_digits=10)),
                ('bad_review_threshold', models.PositiveIntegerField(default=3, help_text='Number of bad reviews before suspension')),
                ('review_rating_bad', models.PositiveIntegerField(default=2, help_text="Rating considered 'bad' (e.g., 2 stars or below)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('max_listing_duration_days', models.PositiveIntegerField(default=30, help_text='Maximum days a listing stays active')),
                ('auto_delete_sold_items', models.BooleanField(default=True, help_text='Auto-delete sold items after recording stats')),
                ('require_geocode', models.BooleanField(default=True, help_text='Require geocode for all listings')),
                ('allow_buyer_listings', models.BooleanField(default=True, help_text='Allow buyers to list items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crossroad Deal Configuration',
                'verbose_name_plural': 'Crossroad Deal Configuration',
            },
        ),
        migrations.CreateModel(
            name='PrivacyDisclosureRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('contact_phone', 'Contact Phone'), ('contact_email', 'Contact Email'), ('price', 'Price'), ('exact_location', 'Exact Location'), ('geocode', 'Geocode'), ('seller_name', 'Seller Name'), ('product_condition', 'Product Condition'), ('quantity_available', 'Quantity Available')], max_length=50, unique=True)),
                ('default_disclosure', models.CharField(choices=[('immediately', 'Immediately (Public)'), ('after_interest', 'After Express Interest'), ('after_add_to_cart', 'After Add to Cart'), ('after_payment', 'After Payment'), ('after_order_complete', 'After Order Complete'), ('never', 'Never (Keep Private)')], default='immediately', help_text='Default disclosure timing for this field', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False, help_text='Must be disclosed at some point')),
            ],
            options={
                'verbose_name': 'Privacy Disclosure Rule',
                'verbose_name_plural': 'Privacy Disclosure Rules',
            },
        ),
        migrations.CreateModel(
            name='CrossroadListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('like_new', 'Like New'), ('good', 'Good Condition'), ('fair', 'Fair Condition'), ('poor', 'Poor Condition')], default='good', max_length=20)),
                ('image_1', models.ImageField(help_text='Primary image', upload_to='crossroad_deals/listings/')),
                ('image_2', models.ImageField(blank=True, help_text='Secondary image (optional)', null=True, upload_to='crossroad_deals/listings/')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('geocode', models.CharField(help_text='Required geocode for pickup/delivery', max_length=100)),
                ('location_description', models.CharField(blank=True, help_text="General area (e.g., 'Serekunda Market Area')", max_length=200)),
                ('show_seller_name', models.BooleanField(default=False)),
                ('show_exact_location', models.BooleanField(default=False)),
                ('price_disclosure', models.CharField(choices=[('immediately', 'Immediately (Public)'), ('after_interest', 'After Express Interest'), ('after_add_to_cart', 'After Add to Cart'), ('after_payment', 'After Payment'), ('after_order_complete', 'After Order Complete'), ('never', 'Never (Keep Private)')], default='immediately', max_length=30)),
                ('contact_disclosure', models.CharField(choices=[('immediately', 'Immediately (Public)'), ('after_interest', 'After Express Interest'), ('after_add_to_cart', 'After Add to Cart'), ('after_payment', 'After Payment'), ('after_order_complete', 'After Order Complete'), ('never', 'Never (Keep Private)')], default='after_add_to_cart', max_length=30)),
                ('location_disclosure', models.CharField(choices=[('immediately', 'Immediately (Public)'), ('after_interest', 'After Express Interest'), ('after_add_to_cart', 'After Add to Cart'), ('after_payment', 'After Payment'), ('after_order_complete', 'After Order Complete'), ('never', 'Never (Keep Private)')], default='after_order_complete', max_length=30)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold_out', 'Sold Out'), ('suspended', 'Suspended'), ('banned', 'Banned'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('is_vetted', models.BooleanField(default=False)),
                ('vetted_at', models.DateTimeField(blank=True, null=True)),
                ('listing_fee_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vetting_fee_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sold_out_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossroad_listings', to=settings.AUTH_USER_MODEL)),
                ('vetted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetted_crossroad_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossroadOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_method', models.CharField(choices=[('easy_move', 'Easy Move Logistics'), ('direct_pickup', 'Direct Pickup')], default='easy_move', max_length=20)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('requested_vetting', models.BooleanField(default=False)),
                ('vetting_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vetting_completed', models.BooleanField(default=False)),
                ('vetting_notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('pickup_scheduled', 'Pickup Scheduled'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('buyer_geocode', models.CharField(blank=True, max_length=100)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crossroad_orders', to=settings.AUTH_USER_MODEL)),
                ('buyer_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crossroad_orders', to='accounts.device')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crossroad_deals.crossroadlisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossroadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('receipt_data', models.JSONField(help_text='Complete order details at receipt time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='crossroad_deals.crossroadorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossroadReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField()),
                ('product_as_described', models.BooleanField(default=True)),
                ('would_buy_again', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for review')),
                ('flagged_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='crossroad_deals.crossroadorder')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossroad_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossroad_reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('listing_create', 'Created Listing'), ('listing_view', 'Viewed Listing'), ('order_create', 'Created Order'), ('order_view', 'Viewed Order'), ('payment_attempt', 'Payment Attempt'), ('review_submit', 'Submitted Review')], max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossroad_activities', to='accounts.device')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crossroad_deals.crossroadlisting')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crossroad_deals.crossroadorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossroad_device_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='crossroad_deals.crossroadlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossroad_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingSaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.UUIDField()),
                ('title', models.CharField(max_length=200)),
                ('quantity_listed', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('published_at', models.DateTimeField()),
                ('sold_out_at', models.DateTimeField()),
                ('time_to_sell_out', models.DurationField(help_text='Time taken to sell out')),
                ('was_vetted', models.BooleanField(default=False)),
                ('listing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vetting_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crossroad_sale_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sold_out_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('bad_reviews', 'Multiple Bad Reviews'), ('illegal_activity', 'Illegal Activity'), ('fraud', 'Fraudulent Behavior'), ('multiple_complaints', 'Multiple Complaints'), ('admin_decision', 'Admin Decision')], max_length=50)),
                ('description', models.TextField()),
                ('bad_review_count', models.PositiveIntegerField(default=0)),
                ('is_permanent_ban', models.BooleanField(default=False)),
                ('auto_suspended', models.BooleanField(default=False, help_text='Auto-suspended by system')),
                ('suspended_at', models.DateTimeField(auto_now_add=True)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('is_lifted', models.BooleanField(default=False)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_lifted', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossroad_suspensions', to=settings.AUTH_USER_MODEL)),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-suspended_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crossroadlisting',
            index=models.Index(fields=['status', '-created_at'], name='crossroad_d_status_7a8eef_idx'),
        ),
        migrations.AddIndex(
            model_name='crossroadlisting',
            index=models.Index(fields=['seller', '-created_at'], name='crossroad_d_seller__497713_idx'),
        ),
        migrations.AddIndex(
            model_name='crossroadlisting',
            index=models.Index(fields=['listing_id'], name='crossroad_d_listing_0e6b67_idx'),
        ),
        migrations.AddIndex(
            model_name='crossroadorder',
            index=models.Index(fields=['buyer', '-created_at'], name='crossroad_d_buyer_i_14c5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='crossroadorder',
            index=models.Index(fields=['listing', '-created_at'], name='crossroad_d_listing_8c8ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='crossroadorder',
            index=models.Index(fields=['status', '-created_at'], name='crossroad_d_status_92737c_idx'),
        ),
        migrations.AddIndex(
            model_name='crossroadreview',
            index=models.Index(fields=['seller', '-created_at'], name='crossroad_d_seller__665b79_idx'),
        ),
        migrations.AddIndex(
            model_name='crossroadreview',
            index=models.Index(fields=['rating'], name='crossroad_d_rating_6c8a21_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceactivitylog',
            index=models.Index(fields=['device', '-created_at'], name='crossroad_d_device__033d11_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceactivitylog',
            index=models.Index(fields=['user', '-created_at'], name='crossroad_d_user_id_e82b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceactivitylog',
            index=models.Index(fields=['action_type', '-created_at'], name='crossroad_d_action__1f6950_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listinginterest',
            unique_together={('listing', 'user')},
        ),
        migrations.AddIndex(
            model_name='listingsalerecord',
            index=models.Index(fields=['-sold_out_at'], name='crossroad_d_sold_ou_3bf796_idx'),
        ),
        migrations.AddIndex(
            model_name='listingsalerecord',
            index=models.Index(fields=['seller', '-sold_out_at'], name='crossroad_d_seller__58f783_idx'),
        ),
    ]
