# Generated by Django 5.2.3 on 2025-07-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_product_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(default=1111111),
            preserve_default=False,
        ),
    ]
