# Generated by Django 5.2.3 on 2025-07-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
