# Generated by Django 5.2.3 on 2025-07-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_remove_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrity_name', models.CharField(max_length=100)),
                ('celebrity_title', models.CharField(blank=True, max_length=200)),
                ('celebrity_image', models.ImageField(blank=True, null=True, upload_to='celebrities/')),
                ('testimonial', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('featured_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='celebrity_features', to='marketplace.product')),
            ],
            options={
                'ordering': ['featured_order', '-created_at'],
            },
        ),
    ]
