# Generated by Django 5.2.3 on 2025-07-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_celebrityfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrityfeature',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celebrityfeature',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celebrityfeature',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
