# Generated by Django 5.2.3 on 2025-07-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_celebrityfeature_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrityfeature',
            name='YouTube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
