# Generated by Django 5.2.3 on 2025-07-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_celebrityfeature_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebrityfeature',
            old_name='YouTube',
            new_name='tiktok_link',
        ),
        migrations.AddField(
            model_name='celebrityfeature',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
