# Generated by Django 5.2.3 on 2025-07-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_rename_youtube_celebrityfeature_tiktok_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebrityfeature',
            old_name='youtube',
            new_name='youtube_link',
        ),
    ]
