# Generated by Django 5.2.3 on 2025-07-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_30_day_return',
            field=models.BooleanField(default=False, help_text='Enable if product is eligible for 30-day return policy.'),
        ),
    ]
