# Generated by Django 5.2.3 on 2025-07-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_productfeature_productfeatureoption_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
