# Generated by Django 5.2.4 on 2025-07-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
