# Generated by Django 5.2.4 on 2025-07-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_product_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction_reserve_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested reserve price for auctions', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='auction_starting_bid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested starting bid for auctions', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_for_auction',
            field=models.BooleanField(default=True),
        ),
    ]
