# Generated by Django 5.2.4 on 2025-07-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_alter_productimage_options_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productimage',
            name='marketplace_product_89f9ab_idx',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variants',
            field=models.ManyToManyField(blank=True, help_text="Variants this image represents (e.g., 'Red', 'Large', 'Cotton')", related_name='images', to='marketplace.productfeatureoption'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Set as primary image for these variants'),
        ),
    ]
