# Generated by Django 5.2.4 on 2025-07-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0032_remove_productimage_marketplace_product_89f9ab_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='auction_reserve_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='auction_starting_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
