# Generated by Django 5.2.4 on 2025-07-30 11:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_alter_product_auction_reserve_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='last_known_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='last_known_stock',
            field=models.IntegerField(default=0),
        ),
    ]
