# Generated by Django 5.2.4 on 2025-08-01 07:07

import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0034_wishlist_last_known_price_wishlist_last_known_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'indexes': [models.Index(django.db.models.functions.text.Lower('email'), name='idx_subscription_email_ci')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_subscription_email_ci')],
            },
        ),
    ]
