# Generated by Django 5.2.5 on 2025-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Logistics', 'Logistics'), ('Operations', 'Operations'), ('Customer Support', 'Customer Support'), ('Sales & Marketing', 'Sales & Marketing'), ('Design', 'Design'), ('Finance', 'Finance')], max_length=32)),
                ('location', models.CharField(default='Banjul, GM', help_text='City, Country or Remote', max_length=120)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-time', max_length=16)),
                ('remote_friendly', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, help_text='1–3 sentences shown at top of detail page')),
                ('description', models.TextField(help_text='Full role description in HTML/Markdown allowed')),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='List of bullet points')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='List of bullet points')),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'department'], name='marketplace_is_acti_57a5ba_idx'), models.Index(fields=['slug'], name='marketplace_slug_8e4152_idx')],
            },
        ),
    ]
