# Generated by Django 5.2.5 on 2025-09-14 03:36

import django.utils.timezone
import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0037_careerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('summary', models.TextField(help_text='1–3 sentences shown on listing.')),
                ('body', models.TextField(help_text='Full body (HTML/Markdown allowed).')),
                ('category', models.CharField(choices=[('company', 'Company'), ('product', 'Product'), ('partnership', 'Partnership'), ('logistics', 'Logistics'), ('finance', 'Finance'), ('csr', 'CSR'), ('other', 'Other')], default='company', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=marketplace.models.press_hero_upload)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_at'],
                'indexes': [models.Index(fields=['is_published', 'publish_at'], name='marketplace_is_publ_6938d3_idx'), models.Index(fields=['slug'], name='marketplace_slug_e3c689_idx'), models.Index(fields=['category'], name='marketplace_categor_a8c250_idx')],
            },
        ),
    ]
