# Generated by Django 5.2.5 on 2025-09-14 04:36

import django.utils.timezone
import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0038_pressrelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('event_type', models.CharField(choices=[('earnings', 'Earnings Call'), ('agm', 'Annual General Meeting'), ('investor_call', 'Investor Call'), ('other', 'Other')], default='other', max_length=32)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('registration_url', models.URLField(blank=True)),
                ('replay_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('financial_report', 'Financial Report'), ('shareholder_letter', 'Shareholder Letter'), ('presentation', 'Presentation'), ('governance', 'Governance & Policies'), ('press_kit', 'Press Kit'), ('other', 'Other')], default='financial_report', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=marketplace.models.investor_doc_upload)),
                ('external_url', models.URLField(blank=True, help_text='Optional external link if file is hosted elsewhere.')),
                ('is_published', models.BooleanField(default=True)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_at'],
                'indexes': [models.Index(fields=['is_published', 'publish_at'], name='marketplace_is_publ_c722c3_idx'), models.Index(fields=['slug'], name='marketplace_slug_4dea23_idx'), models.Index(fields=['category'], name='marketplace_categor_6e53e4_idx')],
            },
        ),
    ]
