# Generated by Django 5.2.5 on 2025-11-08 04:36

import django.db.models.deletion
import marketplace.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0039_investorevent_investordocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=12)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('left', 'Left'), ('blocked', 'Blocked')], default='joined', max_length=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_cart_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(default=marketplace.models._invite_code, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('checkout', 'CheckoutInProgress'), ('locked', 'Locked'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='marketplace.cart')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_social_carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('wave', 'Wave'), ('qmoney', 'Qmoney'), ('afrimoney', 'Afrimoney'), ('gamswitch', 'Gamswitch'), ('cash', 'Cash')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('init', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='init', max_length=12)),
                ('provider_ref', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='marketplace.cartmember')),
                ('social_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='marketplace.socialcart')),
            ],
        ),
        migrations.AddField(
            model_name='cartmember',
            name='social_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='marketplace.socialcart'),
        ),
        migrations.CreateModel(
            name='CartInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=marketplace.models._invite_code, max_length=64, unique=True)),
                ('invited_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invited_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_cart_invites', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_cart_invites', to=settings.AUTH_USER_MODEL)),
                ('social_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='marketplace.socialcart')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('items_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='marketplace.cartmember')),
                ('social_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_shares', to='marketplace.socialcart')),
            ],
            options={
                'unique_together': {('social_cart', 'member')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartmember',
            unique_together={('social_cart', 'user')},
        ),
    ]
