# Generated by Django 5.2.5 on 2025-11-09 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0041_alter_cartitem_unique_together_cartitem_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcart',
            name='single_payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_single_payer_for', to='marketplace.cartmember'),
        ),
        migrations.AddField(
            model_name='socialcart',
            name='split_mode',
            field=models.CharField(choices=[('by_items', 'Each pays their items'), ('by_percent', 'Pay by percentage'), ('single_payer', 'One person pays full')], default='by_items', max_length=20),
        ),
    ]
