# Generated by Django 5.2.5 on 2025-11-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0042_socialcart_single_payer_socialcart_split_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='selected_features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
