# Generated by Django 5.2.5 on 2025-11-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0043_alter_cartitem_selected_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='b2b_min_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity for B2B orders.'),
        ),
        migrations.AddField(
            model_name='product',
            name='b2b_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default wholesale price per unit (if any).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='b2b_tier_price',
            field=models.JSONField(blank=True, help_text='Optional tier pricing as a mapping of min_qty -> price. Example: {"10": "480.00", "50": "450.00"}', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available_b2b',
            field=models.BooleanField(default=False, help_text='If true, product can be sold wholesale via B2B.'),
        ),
        migrations.AddField(
            model_name='product',
            name='visible_in_b2b',
            field=models.BooleanField(default=False, help_text='Show product in B2B marketplace for store-to-store buying.'),
        ),
        migrations.AddField(
            model_name='product',
            name='visible_in_b2c',
            field=models.BooleanField(default=True, help_text='Show product on normal EasyMarket (retail) site.'),
        ),
    ]
