# Generated by Django 5.2.10 on 2026-01-15 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0045_add_sku_to_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_trending',
            field=models.BooleanField(default=False, help_text='Show in trending section (requires active trending campaign)'),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign name (internal)', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('title', models.CharField(help_text='Public-facing campaign title', max_length=200)),
                ('description', models.TextField(help_text='Campaign description for customers')),
                ('campaign_type', models.CharField(choices=[('flash_sale', 'Flash Sale'), ('trending', 'Trending Promotion'), ('seasonal', 'Seasonal Offer'), ('bundle', 'Bundle Deal'), ('clearance', 'Clearance Sale'), ('new_arrival', 'New Arrival')], default='flash_sale', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaigns/banners/')),
                ('background_color', models.CharField(default='#FF6B35', help_text='Hex color code', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=7)),
                ('enable_wheel', models.BooleanField(default=True, help_text='Show spinning wheel for this campaign')),
                ('wheel_prizes', models.JSONField(blank=True, default=list, help_text='List of prizes like [{"label": "10% OFF", "probability": 0.3}, ...]')),
                ('max_spins_per_user', models.IntegerField(default=1, help_text='Maximum spins per user')),
                ('require_login', models.BooleanField(default=False, help_text='Require login to participate')),
                ('total_views', models.IntegerField(default=0)),
                ('total_spins', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='active_campaign',
            field=models.ForeignKey(blank=True, help_text='Current active campaign for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.campaign'),
        ),
        migrations.CreateModel(
            name='CampaignProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('special_price', 'Special Price')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this product in the campaign')),
                ('campaign_stock', models.IntegerField(blank=True, help_text='Limited stock for campaign', null=True)),
                ('stock_sold', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_products', to='marketplace.campaign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_products', to='marketplace.product')),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WheelSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('prize_won', models.CharField(max_length=100)),
                ('prize_type', models.CharField(choices=[('discount', 'Discount'), ('free_shipping', 'Free Shipping'), ('gift', 'Free Gift'), ('points', 'Loyalty Points'), ('nothing', 'Try Again')], default='discount', max_length=20)),
                ('prize_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('promo_code', models.CharField(blank=True, help_text='Generated promo code for this prize', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='marketplace.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wheel_spins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'start_date'], name='marketplace_status_a0079f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['slug'], name='marketplace_slug_2c6af0_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active'], name='marketplace_is_acti_e7b0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignproduct',
            index=models.Index(fields=['campaign', 'is_featured'], name='marketplace_campaig_a69288_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignproduct',
            index=models.Index(fields=['position'], name='marketplace_positio_0085e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignproduct',
            unique_together={('campaign', 'product')},
        ),
        migrations.AddIndex(
            model_name='wheelspin',
            index=models.Index(fields=['campaign', 'user'], name='marketplace_campaig_392fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='wheelspin',
            index=models.Index(fields=['session_key'], name='marketplace_session_02a467_idx'),
        ),
        migrations.AddIndex(
            model_name='wheelspin',
            index=models.Index(fields=['is_redeemed'], name='marketplace_is_rede_67d379_idx'),
        ),
    ]
