# Generated by Django 5.2.10 on 2026-01-16 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0046_product_show_in_trending_campaign_and_more'),
        ('orders', '0027_orderitem_current_shipment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wheelspin',
            options={'ordering': ['-spun_at'], 'verbose_name': 'Wheel Spin', 'verbose_name_plural': 'Wheel Spins'},
        ),
        migrations.RemoveIndex(
            model_name='wheelspin',
            name='marketplace_session_02a467_idx',
        ),
        migrations.RemoveField(
            model_name='wheelspin',
            name='created_at',
        ),
        migrations.AddField(
            model_name='wheelspin',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order where this prize was redeemed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wheel_prizes_used', to='orders.order'),
        ),
        migrations.AddField(
            model_name='wheelspin',
            name='spun_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wheelspin',
            name='campaign',
            field=models.ForeignKey(help_text='The campaign this spin belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='marketplace.campaign'),
        ),
        migrations.AlterField(
            model_name='wheelspin',
            name='is_redeemed',
            field=models.BooleanField(default=False, help_text='Has this prize been used in an order?'),
        ),
        migrations.AlterField(
            model_name='wheelspin',
            name='prize_type',
            field=models.CharField(choices=[('discount', 'Percentage Discount'), ('fixed_amount', 'Fixed Amount Discount'), ('free_shipping', 'Free Shipping'), ('nothing', 'No Prize / Try Again')], default='discount', help_text='Type of prize won', max_length=50),
        ),
        migrations.AlterField(
            model_name='wheelspin',
            name='prize_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (e.g., 10 for 10%) or fixed amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wheelspin',
            name='prize_won',
            field=models.CharField(help_text="Display name of prize (e.g., '10% OFF', 'Free Shipping')", max_length=200),
        ),
        migrations.AlterField(
            model_name='wheelspin',
            name='promo_code',
            field=models.OneToOneField(blank=True, help_text='Auto-generated promo code for this prize', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wheel_spin', to='orders.promocode'),
        ),
        migrations.AlterField(
            model_name='wheelspin',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session key for anonymous users', max_length=255),
        ),
        migrations.AlterField(
            model_name='wheelspin',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who spun (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wheel_spins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wheelspin',
            name='user_agent',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name='wheelspin',
            index=models.Index(fields=['campaign', 'session_key'], name='marketplace_campaig_5dee0c_idx'),
        ),
        migrations.AddIndex(
            model_name='wheelspin',
            index=models.Index(fields=['spun_at'], name='marketplace_spun_at_ebdd8e_idx'),
        ),
    ]
