# Generated by Django 5.2.10 on 2026-01-17 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_country_flag_emoji'),
        ('marketplace', '0047_alter_wheelspin_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=models.ForeignKey(blank=True, help_text='Currency used when setting the price (for conversion tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_priced_in', to='accounts.currency'),
        ),
    ]
