# Generated by Django 5.2.10 on 2026-01-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0050_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatureoption',
            name='color_code',
            field=models.CharField(blank=True, help_text='Hex color code (e.g., #FF0000 for red)', max_length=7, null=True),
        ),
    ]
