# Generated by Django 5.2.4 on 2025-07-20 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_is_read_chatmessage_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
