# Generated by Django 5.2.5 on 2025-12-14 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatthread_created_at'),
        ('marketplace', '0044_alter_product_options_product_b2b_min_quantity_and_more'),
        ('orders', '0024_chatmessage_image_alter_chatmessage_content_and_more'),
        ('stores', '0020_b2border_tracking_note_b2border_tracking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chatthread',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order context (post-order chat).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='orders.order'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product context (pre-order chat).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store context for chat (required for product/order chats).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'timestamp'], name='chat_chatme_thread__a19d84_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'is_read'], name='chat_chatme_thread__a0f205_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['store', '-updated_at'], name='chat_chatth_store_i_355df3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['order'], name='chat_chatth_order_i_a4aa6d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['product'], name='chat_chatth_product_10dad1_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.CheckConstraint(condition=models.Q(('order__isnull', True), ('product__isnull', True), _connector='OR'), name='thread_not_both_product_and_order'),
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', True), ('store__isnull', False), _connector='OR'), name='thread_product_requires_store'),
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.CheckConstraint(condition=models.Q(('order__isnull', True), ('store__isnull', False), _connector='OR'), name='thread_order_requires_store'),
        ),
    ]
