"""
Django settings for easymarket project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-=8goozz#9*r621mccr6m45osd$)x=k9^w%ijb&k*gy%srw(90-')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get('DEBUG', 1)))

ALLOWED_HOSTS = ['*']

# Authentication settings
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'  # Change to your desired redirect after login
LOGOUT_REDIRECT_URL = '/'

# Session settings
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Security settings (for production)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
    'accounts',
    'marketplace',
    'orders',
    'payments',
    'logistics',
    'reviews',
    'stock',
    'chat',
    'stores',
    'finance',
    'auction',
    'helpdesk',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'easymarket.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'marketplace.context_processors.cart_count',
                'marketplace.context_processors.wishlist_count',
                'marketplace.context_processors.search_context',
                'orders.context_processors.pending_orders_count',
                'reviews.context_processors.global_review_stats',
                'auction.context_processors.auction_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'easymarket.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Message tags for Bootstrap/custom styling
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

# Configure these according to your email provider
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Change to your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'equallify.info@gmail.com'  # Your email
EMAIL_HOST_PASSWORD = 'ozlo bvfv cbcs bypx'  # Your email password or app password
DEFAULT_FROM_EMAIL = 'EasyMarket <baboucarrfoon@gmail.com>'
EMAIL_AUCTION_SETTINGS = {
    'OUTBID_NOTIFICATION': True,
    'AUCTION_ENDING_NOTIFICATION': True,
    'AUCTION_WON_NOTIFICATION': True,
    'NEW_BID_NOTIFICATION_SELLER': True,
}
# WhatsApp
TWILIO_ACCOUNT_SID = 'ACa0ca58dacb6f9255c9efb3eeaa17026c'
TWILIO_AUTH_TOKEN = '5106264d473ae30e893d039250be41e3'
TWILIO_WHATSAPP_NUMBER = 'whatsapp:+14155238886'

LOGISTICS_EMAIL = 'baboucarrfoon@gmail.com'
LOGISTICS_PHONE = '+2203930160'

EMAIL_TIMEOUT = 30
EMAIL_USE_LOCALTIME = True


# Notification rate limiting
NOTIFICATION_SETTINGS = {
    'EMAIL_RATE_LIMIT': 100,  # per hour
    'WHATSAPP_RATE_LIMIT': 50,  # per hour
    'RETRY_ATTEMPTS': 3,
    'RETRY_DELAY': 300,  # 5 minutes
}

# Celery for async notifications (recommended)
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SEARCH_RESULTS_PER_PAGE = 12
SEARCH_SUGGESTIONS_LIMIT = 8
SEARCH_MIN_QUERY_LENGTH = 2

# settings.py
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'  # Where to go after successful login
LOGOUT_REDIRECT_URL = '/'  # Where to go after logout

# Google Maps API Key (optional but recommended for better geocoding)
GOOGLE_MAPS_API_KEY = 'your_google_maps_api_key_here'

# Plus Code settings
PLUS_CODE_SETTINGS = {
    'DEFAULT_COUNTRY': 'Gambia',
    'DEFAULT_REGION_CENTER': (13.4432, -15.3101),  # Gambia center
    'GEOCODING_TIMEOUT': 10,  # seconds
    'USE_GOOGLE_GEOCODING': True,
    'FALLBACK_TO_OSM': True,
}

# Auction-specific settings
AUCTION_SETTINGS = {
    'AUTO_END_AUCTIONS': True,
    'NOTIFICATION_EMAILS': True,
    'MAX_IMAGES_PER_AUCTION': 5,
    'DEFAULT_AUCTION_DURATION_DAYS': 7,
    'MIN_AUCTION_DURATION_HOURS': 1,
    'MAX_AUCTION_DURATION_DAYS': 30,
    'FEATURED_AUCTION_COST': 10.00,
    'AUTO_EXTEND_MINUTES': 5,
    'DEFAULT_COMMISSION_RATE': 5.0,  # 5% default commission
    'MINIMUM_BID_INCREMENT': 1.00,
}

# Integration with existing payment system
PAYMENT_INTEGRATION = {
    'AUCTION_PAYMENT_REQUIRED': True,
    'AUCTION_FEES': {
        'LISTING_FEE': 0.50,
        'SUCCESS_FEE_PERCENTAGE': 3.5,
        'FEATURED_LISTING_FEE': 10.00,
    }
}