"""
Django settings for easymarket project.
Generated by 'django-admin startproject' using Django 5.2.x
"""
from pathlib import Path
from decouple import config, Csv
import dj_database_url

# -----------------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------
# Core security / env
# -----------------------------------------------------------------------------
SECRET_KEY = config("SECRET_KEY", default="django-insecure-temp-key")
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="*", cast=Csv())
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())

# Optional: lock admin URL via env (e.g., /super-admin/)
ADMIN_URL = config("ADMIN_URL", default="admin/")

# -----------------------------------------------------------------------------
# Session
# -----------------------------------------------------------------------------
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# -----------------------------------------------------------------------------
# Security headers (tighten when DEBUG=False)
# -----------------------------------------------------------------------------
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS (adjust max-age as needed)
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# -----------------------------------------------------------------------------
# Applications
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.sites",

    # Auth / Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "django_celery_beat",

    # UI
    "crispy_forms",
    "crispy_bootstrap5",
    "widget_tweaks",

    # Project apps
    "accounts",
    "marketplace",
    "orders",
    "payments",
    "reviews",
    "stock",
    "chat",
    "stores",
    "finance",
    "auction",
    "helpdesk",
    "analytics",
    "supply_chain",
    "logistics.apps.LogisticsConfig",
]

SITE_ID = config("SITE_ID", default=1, cast=int)
AUTH_USER_MODEL = "accounts.User"
SITE_BASE_URL = "www.easymarket.vip"

# -----------------------------------------------------------------------------
# Allauth / Authentication
# -----------------------------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    "accounts.auth_backends.UsernameOrPhoneOrEmailBackend",   # custom first
    "allauth.account.auth_backends.AuthenticationBackend",
]

# If you want email verification behavior configurable via env
ACCOUNT_EMAIL_VERIFICATION = config("ACCOUNT_EMAIL_VERIFICATION", default="optional")
ACCOUNT_UNIQUE_EMAIL = config("ACCOUNT_UNIQUE_EMAIL", default=True, cast=bool)

# "ACCOUNT_LOGIN_METHODS" is newer; fall back to classic flags if needed
ACCOUNT_SIGNUP_FIELDS = ['username*', 'password1*', 'password2*', 'email']

ACCOUNT_SIGNUP_FORM_CLASS = "accounts.forms.CustomSignupForm"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": config("GOOGLE_CLIENT_ID", default=""),
            "secret": config("GOOGLE_CLIENT_SECRET", default=""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"prompt": "select_account"},
    }
}

LOGIN_URL = "/accounts/sign_in/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# -----------------------------------------------------------------------------
# Middleware / URLs / Templates
# -----------------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "analytics.middleware.AnalyticsMiddleware",
]

ROOT_URLCONF = "easymarket.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "marketplace.context_processors.cart_count",
                "marketplace.context_processors.wishlist_count",
                "marketplace.context_processors.search_context",
                "orders.context_processors.pending_orders_count",
                "reviews.context_processors.global_review_stats",
                "auction.context_processors.auction_counts",
                "marketplace.context_processors.nav_categories",
                "analytics.context_processors.analytics_metrics",
                "analytics.context_processors.store_analytics_kpis",
                "logistics.context_processors.logistics_nav_counts",
                "logistics.context_processors.notification_context",
                "accounts.context_processors.currency_context",
            ],
        },
    },
]

WSGI_APPLICATION = "easymarket.wsgi.application"

# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------
DATABASES = {
    "default": dj_database_url.parse(
        config("DATABASE_URL", default=f"sqlite:///{BASE_DIR/'db.sqlite3'}"),
        conn_max_age=config("DB_CONN_MAX_AGE", default=60, cast=int),
    )
}

# -----------------------------------------------------------------------------
# Password validation
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------------------------------------------------------
# i18n / TZ
# -----------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = config("TIME_ZONE", default="UTC")
USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------------------------
# Messages (Bootstrap-friendly)
# -----------------------------------------------------------------------------
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: "debug",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "error",
}

# -----------------------------------------------------------------------------
# Email
# -----------------------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=30, cast=int)
EMAIL_USE_LOCALTIME = config("EMAIL_USE_LOCALTIME", default=True, cast=bool)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="EasyMarket <noreply@easymarket.com>")

EMAIL_AUCTION_SETTINGS = {
    "OUTBID_NOTIFICATION": True,
    "AUCTION_ENDING_NOTIFICATION": True,
    "AUCTION_WON_NOTIFICATION": True,
    "NEW_BID_NOTIFICATION_SELLER": True,
}

# -----------------------------------------------------------------------------
# Twilio / WhatsApp
# -----------------------------------------------------------------------------
TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN", default="")
TWILIO_WHATSAPP_NUMBER = config("TWILIO_WHATSAPP_NUMBER", default="")

# -----------------------------------------------------------------------------
# Business contacts
# -----------------------------------------------------------------------------
LOGISTICS_EMAIL = config("LOGISTICS_EMAIL", default="")
LOGISTICS_PHONE = config("LOGISTICS_PHONE", default="")
DEFAULT_CURRENCY = 'GMD'  # or 'USD', 'EUR', etc.

# -----------------------------------------------------------------------------
# Rate limiting (notifications)
# -----------------------------------------------------------------------------
NOTIFICATION_SETTINGS = {
    "EMAIL_RATE_LIMIT": config("EMAIL_RATE_LIMIT", default=100, cast=int),   # per hour
    "WHATSAPP_RATE_LIMIT": config("WHATSAPP_RATE_LIMIT", default=50, cast=int),  # per hour
    "RETRY_ATTEMPTS": config("NOTIFY_RETRY_ATTEMPTS", default=3, cast=int),
    "RETRY_DELAY": config("NOTIFY_RETRY_DELAY", default=300, cast=int),  # seconds
}

# -----------------------------------------------------------------------------
# Celery / Redis
# -----------------------------------------------------------------------------
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://localhost:6379")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TIMEZONE = 'UTC'

# Celery Beat settings
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# -----------------------------------------------------------------------------
# Static & Media
# -----------------------------------------------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# -----------------------------------------------------------------------------
# Crispy Forms
# -----------------------------------------------------------------------------
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# -----------------------------------------------------------------------------
# Defaults
# -----------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
SEARCH_RESULTS_PER_PAGE = 12
SEARCH_SUGGESTIONS_LIMIT = 8
SEARCH_MIN_QUERY_LENGTH = 2

EXCHANGE_RATE_API_KEY = config("EXCHANGE_RATE_API_KEY", default="")
# -----------------------------------------------------------------------------
# Google Maps / Geocoding
# -----------------------------------------------------------------------------
GOOGLE_MAPS_API_KEY = config("GOOGLE_MAPS_API_KEY", default="")
PLUS_CODE_SETTINGS = {
    "DEFAULT_COUNTRY": config("PLUS_DEFAULT_COUNTRY", default="Gambia"),
    "DEFAULT_REGION_CENTER": (
        config("PLUS_DEFAULT_LAT", default=13.4432, cast=float),
        config("PLUS_DEFAULT_LNG", default=-15.3101, cast=float),
    ),
    "GEOCODING_TIMEOUT": config("GEOCODING_TIMEOUT", default=10, cast=int),
    "USE_GOOGLE_GEOCODING": config("USE_GOOGLE_GEOCODING", default=True, cast=bool),
    "FALLBACK_TO_OSM": config("FALLBACK_TO_OSM", default=True, cast=bool),
}

# -----------------------------------------------------------------------------
# Auction / Payments (business rules)
# -----------------------------------------------------------------------------
AUCTION_SETTINGS = {
    "AUTO_END_AUCTIONS": True,
    "NOTIFICATION_EMAILS": True,
    "MAX_IMAGES_PER_AUCTION": 5,
    "DEFAULT_AUCTION_DURATION_DAYS": 7,
    "MIN_AUCTION_DURATION_HOURS": 1,
    "MAX_AUCTION_DURATION_DAYS": 30,
    "FEATURED_AUCTION_COST": 10.00,
    "AUTO_EXTEND_MINUTES": 5,
    "DEFAULT_COMMISSION_RATE": 5.0,  # %
    "MINIMUM_BID_INCREMENT": 1.00,
}

PAYMENT_INTEGRATION = {
    "AUCTION_PAYMENT_REQUIRED": True,
    "AUCTION_FEES": {
        "LISTING_FEE": 0.50,
        "SUCCESS_FEE_PERCENTAGE": 3.5,
        "FEATURED_LISTING_FEE": 10.00,
    },
}
