# Generated by Django 5.2.4 on 2025-07-22 01:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0003_chatthread_created_at'),
        ('logistics', '0004_shipmentbox_boxitem'),
        ('marketplace', '0028_product_used'),
        ('orders', '0015_alter_order_tax_rate'),
        ('payments', '0002_payment_notes_payment_payment_date_and_more'),
        ('reviews', '0003_alter_review_unique_together_review_updated_at_and_more'),
        ('stores', '0002_storeinventorytracking_storereturnsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketplace_category', models.ForeignKey(blank=True, help_text='Link to marketplace category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_categories', to='marketplace.category')),
            ],
            options={
                'verbose_name_plural': 'Auction Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('auction_type', models.CharField(choices=[('standard', 'Standard Auction'), ('reserve', 'Reserve Auction'), ('buy_now', 'Auction with Buy Now'), ('dutch', 'Dutch Auction')], default='standard', max_length=20)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('increment_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('auto_extend', models.BooleanField(default=False, help_text='Extend auction if bid placed in last 5 minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auction_images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled'), ('sold', 'Sold'), ('payment_pending', 'Payment Pending')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('shipping_required', models.BooleanField(default=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('international_shipping', models.BooleanField(default=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Commission percentage for this auction', max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('seller_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_product', models.ForeignKey(blank=True, help_text='Link to existing marketplace product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='marketplace.product')),
                ('order', models.OneToOneField(blank=True, help_text='Order created when auction is won', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction', to='orders.order')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction', to='payments.payment')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction', to='logistics.shipment')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='stores.store')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auction.auctioncategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auction_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='auction.auction')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='auction.auction')),
                ('chat_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_questions', to='chat.chatthread')),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_communication', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Rate seller communication (1-5)')),
                ('item_accuracy', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='How accurately was the item described (1-5)')),
                ('shipping_speed', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Rate shipping speed (1-5)')),
                ('would_buy_again', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction_review', to='auction.auction')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction_review', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_winning', models.BooleanField(default=False)),
                ('is_auto_bid', models.BooleanField(default=False)),
                ('max_auto_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notify_outbid', models.BooleanField(default=True)),
                ('notify_ending', models.BooleanField(default=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='auction.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'end_date'], name='auction_auc_status_06b972_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['category', 'status'], name='auction_auc_categor_3a59a2_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['seller', 'status'], name='auction_auc_seller__288e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['store', 'status'], name='auction_auc_store_i_dc7187_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-amount'], name='auction_bid_auction_51aabe_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder', '-timestamp'], name='auction_bid_bidder__d441df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('auction', 'bidder', 'amount')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'auction')},
        ),
    ]
