# Generated by Django 5.2.3 on 2025-07-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_profile_pc_user_verify_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pc',
            new_name='profile_pic',
        ),
    ]
