# Generated by Django 5.2.3 on 2025-07-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_address_country_alter_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='geo_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
