# Generated by Django 5.2.4 on 2025-07-22 03:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('product_add', 'Product Added'), ('product_delete', 'Product Deleted'), ('product_edit', 'Product Setting Changed'), ('bad_rating', 'Bad Rating Reported'), ('store_edit', 'Store Setting Changed'), ('complaint', 'Customer Complaint')], max_length=50)),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('related_model', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
