# Generated by Django 5.2.4 on 2025-07-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adminlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action_type',
            field=models.CharField(choices=[('product_add', 'Product Added'), ('product_edit', 'Product Updated'), ('product_delete', 'Product Deleted'), ('variant_update', 'Product Variant Updated'), ('stock_update', 'Stock Updated'), ('bad_rating', 'Bad Product Rating'), ('store_edit', 'Store Settings Updated'), ('complaint', 'Customer Complaint')], max_length=50),
        ),
    ]
