# Generated by Django 5.2.4 on 2025-07-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_adminlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
