# Generated by Django 5.2.4 on 2025-07-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_adminlog_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
