# Generated by Django 5.2.4 on 2025-07-22 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_adminlog_flagged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
