# Generated by Django 5.2.4 on 2025-07-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_adminlog_flagged_by_adminlog_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
