# Generated by Django 5.2.5 on 2025-08-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_adminlog_reviewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default=123, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
