# Generated by Django 5.2.10 on 2026-01-13 05:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_device_onetimecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 code (e.g., GM, CN, US)', max_length=3, unique=True)),
                ('code3', models.CharField(blank=True, help_text='ISO 3166-1 alpha-3 code (e.g., GMB, CHN, USA)', max_length=3)),
                ('numeric_code', models.CharField(blank=True, help_text='ISO 3166-1 numeric code', max_length=3)),
                ('phone_code', models.CharField(blank=True, help_text='International dialing code (e.g., +220)', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., GMD, USD, EUR, CNY)', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., D, $, €, ¥)', max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places')),
                ('is_base_currency', models.BooleanField(default=False, help_text='Set one currency as base for exchange rates (typically USD or your main currency)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='country_name',
            field=models.CharField(blank=True, help_text='Deprecated: Use country field', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Select country from the list', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='accounts.currency'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, help_text="User's preferred currency for pricing", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_preferring', to='accounts.currency'),
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, help_text='Exchange rate: 1 from_currency = rate × to_currency', max_digits=20)),
                ('source', models.CharField(default='manual', help_text="Source of the rate (e.g., 'exchangerate-api', 'manual', 'fixer.io')", max_length=50)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Rate expiry (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='accounts.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='accounts.currency')),
            ],
            options={
                'verbose_name': 'Currency Exchange Rate',
                'verbose_name_plural': 'Currency Exchange Rates',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency'], name='accounts_cu_from_cu_7acfb1_idx'), models.Index(fields=['-updated_at'], name='accounts_cu_updated_462acc_idx')],
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
