# Generated by Django 5.2.10 on 2026-01-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_country_currency_address_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(blank=True, help_text='Flag emoji for the country', max_length=10),
        ),
    ]
