# Generated by Django 5.2.4 on 2025-07-12 00:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_cartitem_selected_features'),
        ('orders', '0012_return_returnimage_returnitem_returnrefund_and_more'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInventoryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('restock', 'Restock'), ('return_received', 'Return Received'), ('return_restocked', 'Return Restocked'), ('return_discounted', 'Return Discounted'), ('damage', 'Damage/Loss'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('condition', models.CharField(blank=True, choices=[('new', 'Like New'), ('good', 'Good Condition'), ('fair', 'Fair Condition'), ('poor', 'Poor Condition'), ('damaged', 'Damaged')], max_length=20, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
                ('return_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='orders.return')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_tracking', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Inventory Tracking',
                'verbose_name_plural': 'Store Inventory Tracking',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StoreReturnSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_window_days', models.PositiveIntegerField(default=30)),
                ('accept_defective', models.BooleanField(default=True)),
                ('accept_wrong_item', models.BooleanField(default=True)),
                ('accept_wrong_size', models.BooleanField(default=True)),
                ('accept_damaged_shipping', models.BooleanField(default=True)),
                ('accept_not_as_described', models.BooleanField(default=True)),
                ('accept_changed_mind', models.BooleanField(default=False)),
                ('accept_quality_issues', models.BooleanField(default=True)),
                ('auto_approve_returns', models.BooleanField(default=False)),
                ('require_original_packaging', models.BooleanField(default=True)),
                ('require_photos', models.BooleanField(default=True)),
                ('provide_return_label', models.BooleanField(default=True)),
                ('pickup_service_available', models.BooleanField(default=True)),
                ('restocking_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage fee for returns (0-100)', max_digits=5)),
                ('refund_shipping_cost', models.BooleanField(default=False)),
                ('custom_return_policy', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_settings', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Return Settings',
                'verbose_name_plural': 'Store Return Settings',
            },
        ),
        migrations.CreateModel(
            name='StoreMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_items_sold', models.PositiveIntegerField(default=0)),
                ('total_returns', models.PositiveIntegerField(default=0)),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('return_rate_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_inventory_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('low_stock_items', models.PositiveIntegerField(default=0)),
                ('out_of_stock_items', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('repeat_customers', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Metrics',
                'verbose_name_plural': 'Store Metrics',
                'ordering': ['-date'],
                'unique_together': {('store', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StoreShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regions', models.TextField(help_text='Comma-separated list of regions')),
                ('base_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('per_kg_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order amount for free shipping', max_digits=10, null=True)),
                ('estimated_delivery_days', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones', to='stores.store')),
            ],
            options={
                'verbose_name': 'Shipping Zone',
                'verbose_name_plural': 'Shipping Zones',
                'unique_together': {('store', 'name')},
            },
        ),
    ]
