# Generated by Django 5.2.4 on 2025-07-22 02:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storeinventorytracking_storereturnsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='allow_auctions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='auction_commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Commission rate for auctions (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='auto_approve_auctions',
            field=models.BooleanField(default=False, help_text='Automatically approve auctions without admin review'),
        ),
    ]
