# Generated by Django 5.2.4 on 2025-07-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_allow_auctions_store_auction_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accept_cash_risk',
            field=models.BooleanField(default=False),
        ),
    ]
