# Generated by Django 5.2.4 on 2025-07-26 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_storereferral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storereferral',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='storereferral',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='storereferral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storereferral',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='storereferral',
            unique_together={('referrer', 'referred_email', 'store')},
        ),
    ]
