# Generated by Django 5.2.4 on 2025-07-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_storereferral_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='allow_referrals',
            field=models.BooleanField(default=False, help_text='Allow buyers to refer this store and earn rewards.'),
        ),
    ]
