# Generated by Django 5.2.4 on 2025-07-29 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_productpricehistory_storefollow_storenotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='stores_stor_user_id_7f5364_idx'), models.Index(fields=['store'], name='stores_stor_store_i_c3ba71_idx'), models.Index(fields=['created_at'], name='stores_stor_created_aa8512_idx')],
                'unique_together': {('user', 'store')},
            },
        ),
    ]
