# Generated by Django 5.2.5 on 2025-08-22 18:44

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_storefavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('max_placements', models.PositiveIntegerField(default=1)),
                ('max_concurrent_campaigns', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_placements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('homepage_banner', 'Homepage Banner'), ('category_feature', 'Category Feature'), ('trending_carousel', 'Trending Carousel'), ('push_notification', 'Push Notification'), ('email_campaign', 'Email Campaign'), ('deals_page', 'Deals Page'), ('store_spotlight', 'Store Spotlight')], max_length=50), blank=True, default=list, help_text='Which placements this subscription can use', size=None)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='stores.promotionplan')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_subscriptions', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('homepage_banner', 'Homepage Banner'), ('category_feature', 'Category Feature'), ('trending_carousel', 'Trending Carousel'), ('push_notification', 'Push Notification'), ('email_campaign', 'Email Campaign'), ('deals_page', 'Deals Page'), ('store_spotlight', 'Store Spotlight')], max_length=50)),
                ('audience', models.CharField(choices=[('all_buyers', 'All Buyers'), ('store_followers', 'Store Followers'), ('subscribers', 'Email Subscribers')], default='all_buyers', max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('headline', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promotions/banners/')),
                ('scheduled_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('live', 'Live'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_campaigns', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_campaigns', to='stores.store')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='stores.promotionsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['placement', 'status'], name='stores_prom_placeme_4370e7_idx'), models.Index(fields=['scheduled_at', 'expires_at'], name='stores_prom_schedul_f269f1_idx')],
            },
        ),
    ]
