# Generated by Django 5.2.5 on 2025-08-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_subscription'),
        ('stores', '0010_promotionplan_promotionsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncampaign',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products featured in this campaign', related_name='promotion_campaigns', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='promotionplan',
            name='max_products_per_campaign',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
