# Generated by Django 5.2.5 on 2025-11-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_promotioncampaign_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='allows_b2b',
            field=models.BooleanField(default=False, help_text='If enabled, this store can sell in the B2B marketplace.'),
        ),
        migrations.AddField(
            model_name='store',
            name='b2b_description',
            field=models.TextField(blank=True, help_text='Short description for B2B buyers (MOQ, special terms, etc.).', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='b2b_min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount for B2B transactions (optional).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='is_b2b_only',
            field=models.BooleanField(default=False, help_text='If true, store appears ONLY in B2B listings (hidden from normal marketplace).'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_international_supplier',
            field=models.BooleanField(default=False, help_text='Highlight this store as an international B2B supplier.'),
        ),
    ]
