# Generated by Django 5.2.5 on 2025-12-11 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0044_alter_product_options_product_b2b_min_quantity_and_more'),
        ('stores', '0012_store_allows_b2b_store_b2b_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='b2b_contact_email',
            field=models.EmailField(blank=True, help_text='Email address where B2B inquiries should be sent. Defaults to owner email if empty.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='b2b_preferred_channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Email & WhatsApp')], default='email', help_text='Preferred channel for B2B negotiations.', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='b2b_whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for B2B negotiations (include country code).', max_length=30),
        ),
        migrations.CreateModel(
            name='B2BInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('preferred_channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Email + WhatsApp')], default='email', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_inquiries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_inquiries', to='stores.store')),
            ],
        ),
    ]
