# Generated by Django 5.2.5 on 2025-12-12 07:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0044_alter_product_options_product_b2b_min_quantity_and_more'),
        ('stores', '0013_store_b2b_contact_email_store_b2b_preferred_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='B2BCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('requested_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.b2bcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='B2BOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('priced', 'Priced by seller'), ('accepted', 'Accepted by buyer'), ('rejected', 'Rejected by buyer'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('completed', 'Completed')], default='submitted', max_length=20)),
                ('buyer_note', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priced_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_orders', to=settings.AUTH_USER_MODEL)),
                ('cart_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.b2bcart')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_orders', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='B2BOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('requested_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('seller_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.b2border')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.productvariant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='b2bcart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('buyer',), name='uniq_active_b2b_cart_per_buyer'),
        ),
        migrations.AddConstraint(
            model_name='b2bcartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant'), name='uniq_b2b_cart_line'),
        ),
    ]
