# Generated by Django 5.2.5 on 2025-12-12 23:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_b2border_shipping_cost_b2border_shipping_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2border',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
