# Generated by Django 5.2.5 on 2025-12-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_b2border_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2borderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
