# Generated by Django 5.2.5 on 2025-12-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_b2borderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2borderitem',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2borderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='b2borderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Locked unit price used for totals and invoices', max_digits=12, null=True),
        ),
    ]
