# Generated by Django 5.2.5 on 2025-12-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_b2borderitem_shipped_at_b2borderitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2border',
            name='tracking_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2border',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
