# Generated by Django 5.2.9 on 2025-12-31 04:43

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_b2border_tracking_note_b2border_tracking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accent_color',
            field=models.CharField(default='#f59e0b', help_text='Accent color for highlights and CTAs', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FF5733)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='store',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Main background color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FF5733)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='store',
            name='banner_height',
            field=models.CharField(choices=[('small', 'Small (300px)'), ('medium', 'Medium (400px)'), ('large', 'Large (500px)'), ('xlarge', 'Extra Large (600px)')], default='medium', help_text='Height of store banner', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='banner_overlay_opacity',
            field=models.IntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=30, help_text='Darkness of overlay on banner image'),
        ),
        migrations.AddField(
            model_name='store',
            name='cta_button_style',
            field=models.CharField(choices=[('rounded', 'Rounded Corners'), ('square', 'Square Corners'), ('pill', 'Pill Shape')], default='rounded', help_text='Style of buttons throughout store', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='cta_button_text',
            field=models.CharField(default='Shop Now', help_text='Text for main call-to-action buttons', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Add custom CSS to further customize your store appearance', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_animations',
            field=models.BooleanField(default=True, help_text='Enable smooth animations and transitions'),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_best_sellers',
            field=models.BooleanField(default=True, help_text='Show best sellers section'),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_featured_products',
            field=models.BooleanField(default=True, help_text='Show featured products section'),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_hover_effects',
            field=models.BooleanField(default=True, help_text='Enable hover effects on products and buttons'),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_image_optimization',
            field=models.BooleanField(default=True, help_text='Automatically optimize images'),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_lazy_loading',
            field=models.BooleanField(default=True, help_text='Lazy load images for better performance'),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_new_arrivals',
            field=models.BooleanField(default=True, help_text='Show new arrivals section'),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_parallax_banner',
            field=models.BooleanField(default=False, help_text='Enable parallax scrolling effect on banner'),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_testimonials',
            field=models.BooleanField(default=False, help_text='Show customer testimonials section'),
        ),
        migrations.AddField(
            model_name='store',
            name='font_body',
            field=models.CharField(choices=[('inter', 'Inter (Modern Sans-Serif)'), ('roboto', 'Roboto (Clean & Professional)'), ('playfair', 'Playfair Display (Elegant Serif)'), ('montserrat', 'Montserrat (Bold & Modern)'), ('lato', 'Lato (Friendly & Readable)'), ('poppins', 'Poppins (Geometric & Modern)'), ('raleway', 'Raleway (Elegant Sans-Serif)'), ('merriweather', 'Merriweather (Classic Serif)')], default='inter', help_text='Font for body text', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='font_heading',
            field=models.CharField(choices=[('inter', 'Inter (Modern Sans-Serif)'), ('roboto', 'Roboto (Clean & Professional)'), ('playfair', 'Playfair Display (Elegant Serif)'), ('montserrat', 'Montserrat (Bold & Modern)'), ('lato', 'Lato (Friendly & Readable)'), ('poppins', 'Poppins (Geometric & Modern)'), ('raleway', 'Raleway (Elegant Sans-Serif)'), ('merriweather', 'Merriweather (Classic Serif)')], default='poppins', help_text='Font for headings and titles', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='header_message',
            field=models.CharField(blank=True, help_text='Announcement message displayed at top of store (e.g., "Free shipping on orders over $50!")', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn company page URL', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Custom SEO description', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom SEO title (leave blank to use store name)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='mobile_menu_style',
            field=models.CharField(choices=[('bottom', 'Bottom Navigation'), ('sidebar', 'Sidebar Menu'), ('top', 'Top Dropdown')], default='bottom', help_text='Mobile navigation style', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='primary_color',
            field=models.CharField(default='#2563eb', help_text='Main brand color (hex code)', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FF5733)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='store',
            name='product_card_style',
            field=models.CharField(choices=[('shadow', 'Card with Shadow'), ('border', 'Card with Border'), ('minimal', 'Minimal (No Border)'), ('elevated', 'Elevated (Deep Shadow)')], default='shadow', help_text='Style of product cards', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='product_image_shape',
            field=models.CharField(choices=[('square', 'Square'), ('rounded', 'Rounded Corners'), ('circle', 'Circle')], default='square', help_text='Shape of product images', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='product_layout',
            field=models.CharField(choices=[('grid', 'Grid Layout'), ('list', 'List Layout'), ('masonry', 'Masonry Layout'), ('carousel', 'Carousel Layout')], default='grid', help_text='How products are displayed on your store page', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='products_per_row',
            field=models.IntegerField(choices=[(2, '2 products'), (3, '3 products'), (4, '4 products'), (5, '5 products')], default=4, help_text='Number of products per row'),
        ),
        migrations.AddField(
            model_name='store',
            name='secondary_color',
            field=models.CharField(default='#64748b', help_text='Secondary accent color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FF5733)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='store',
            name='show_customer_support_badge',
            field=models.BooleanField(default=True, help_text='Display "24/7 Customer Support" badge'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_free_shipping_badge',
            field=models.BooleanField(default=False, help_text='Display "Free Shipping" badge'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_header_message',
            field=models.BooleanField(default=False, help_text='Display header announcement message'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_map_location',
            field=models.BooleanField(default=False, help_text='Show store location on map'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_money_back_guarantee',
            field=models.BooleanField(default=False, help_text='Display "Money Back Guarantee" badge'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_operating_hours',
            field=models.BooleanField(default=True, help_text='Display business hours on store page'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_product_badges',
            field=models.BooleanField(default=True, help_text='Show "New", "Sale", "Bestseller" badges'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_product_ratings',
            field=models.BooleanField(default=True, help_text='Display star ratings on product cards'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_quick_view',
            field=models.BooleanField(default=True, help_text='Enable quick view button on products'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_secure_checkout_badge',
            field=models.BooleanField(default=True, help_text='Display "Secure Checkout" badge'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_social_links',
            field=models.BooleanField(default=True, help_text='Display social media links'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_store_description',
            field=models.BooleanField(default=True, help_text='Display store description on store page'),
        ),
        migrations.AddField(
            model_name='store',
            name='show_store_stats',
            field=models.BooleanField(default=True, help_text='Show total products, reviews, ratings'),
        ),
        migrations.AddField(
            model_name='store',
            name='text_color',
            field=models.CharField(default='#1e293b', help_text='Primary text color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #FF5733)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AddField(
            model_name='store',
            name='theme_preset',
            field=models.CharField(choices=[('modern', 'Modern & Clean'), ('elegant', 'Elegant & Luxury'), ('vibrant', 'Vibrant & Bold'), ('minimal', 'Minimal & Simple'), ('dark', 'Dark Mode'), ('classic', 'Classic Business'), ('creative', 'Creative & Artistic'), ('professional', 'Professional Corporate')], default='modern', help_text='Choose a pre-designed theme for your store', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='theme_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='store',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='TikTok profile URL', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL', null=True),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['theme_preset', 'status'], name='stores_stor_theme_p_5c64be_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['product_layout'], name='stores_stor_product_ce2fbf_idx'),
        ),
    ]
