# Generated by Django 5.2.9 on 2026-01-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_store_accent_color_store_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
