# Generated by Django 5.2.9 on 2026-01-05 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_supplier_alter_stock_options_stock_last_counted_and_more'),
        ('stores', '0022_store_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='warehouse',
            field=models.OneToOneField(blank=True, help_text="Store's inventory warehouse", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='stock.warehouse'),
        ),
    ]
