# Generated by Django 5.2.10 on 2026-01-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0023_store_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2border',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shipped', 'Shipped to Buyer'), ('priced', 'Priced by seller'), ('accepted', 'Accepted by buyer'), ('rejected', 'Rejected by buyer'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('completed', 'Completed')], default='submitted', max_length=20),
        ),
    ]
