# Generated by Django 5.2.3 on 2025-07-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_promocode_order_promo_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPayment',
        ),
    ]
