# Generated by Django 5.2.3 on 2025-07-07 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delete_orderpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
