# Generated by Django 5.2.3 on 2025-07-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
