# Generated by Django 5.2.4 on 2025-07-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_selected_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='geo_code',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='region',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Gambia', max_length=100),
        ),
    ]
