# Generated by Django 5.2.4 on 2025-07-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_zip_code_shippingaddress_geo_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
    ]
