# Generated by Django 5.2.4 on 2025-07-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_cartitem_selected_features'),
        ('orders', '0010_alter_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promo_codes', to='marketplace.product'),
        ),
    ]
