# Generated by Django 5.2.4 on 2025-07-12 00:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_cartitem_selected_features'),
        ('orders', '0011_promocode_products'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Awaiting Pickup'), ('rejected', 'Rejected'), ('in_transit', 'In Transit to Store'), ('received', 'Received by Store'), ('completed', 'Completed - Refund Processed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason', models.CharField(choices=[('defective', 'Product Defective'), ('wrong_item', 'Wrong Item Received'), ('wrong_size', 'Wrong Size'), ('damaged_shipping', 'Damaged During Shipping'), ('not_as_described', 'Not as Described'), ('changed_mind', 'Changed Mind'), ('quality_issues', 'Quality Issues'), ('other', 'Other')], max_length=20)),
                ('reason_description', models.TextField(help_text='Detailed explanation for the return')),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('logistics_method', models.CharField(choices=[('easymarket_pickup', 'EasyMarket Pickup'), ('buyer_dropoff', 'Buyer Drop-off'), ('courier_service', 'Courier Service')], default='easymarket_pickup', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_pickup_date', models.DateField(blank=True, null=True)),
                ('actual_pickup_date', models.DateTimeField(blank=True, null=True)),
                ('received_at_store_date', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order')),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.return')),
            ],
            options={
                'verbose_name': 'Return Image',
                'verbose_name_plural': 'Return Images',
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('defective', 'Product Defective'), ('wrong_item', 'Wrong Item Received'), ('wrong_size', 'Wrong Size'), ('damaged_shipping', 'Damaged During Shipping'), ('not_as_described', 'Not as Described'), ('changed_mind', 'Changed Mind'), ('quality_issues', 'Quality Issues'), ('other', 'Other')], max_length=20)),
                ('condition', models.CharField(choices=[('new', 'Like New'), ('good', 'Good Condition'), ('fair', 'Fair Condition'), ('poor', 'Poor Condition'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('price_at_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.return')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
            },
        ),
        migrations.CreateModel(
            name='ReturnRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_method', models.CharField(choices=[('original_payment', 'Original Payment Method'), ('store_credit', 'Store Credit'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='original_payment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='orders.return')),
            ],
            options={
                'verbose_name': 'Return Refund',
                'verbose_name_plural': 'Return Refunds',
            },
        ),
        migrations.CreateModel(
            name='ReturnStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Awaiting Pickup'), ('rejected', 'Rejected'), ('in_transit', 'In Transit to Store'), ('received', 'Received by Store'), ('completed', 'Completed - Refund Processed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.return')),
            ],
            options={
                'verbose_name': 'Return Status History',
                'verbose_name_plural': 'Return Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('regular_stock', models.PositiveIntegerField(default=0)),
                ('returned_stock', models.PositiveIntegerField(default=0)),
                ('discounted_stock', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_summary', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Inventory',
                'verbose_name_plural': 'Store Inventories',
                'unique_together': {('store',)},
            },
        ),
    ]
