# Generated by Django 5.2.4 on 2025-07-13 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_cartitem_selected_features'),
        ('orders', '0012_return_returnimage_returnitem_returnrefund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='marketplace.product'),
        ),
    ]
