# Generated by Django 5.2.4 on 2025-07-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipped_to_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
