# Generated by Django 5.2.4 on 2025-07-21 05:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_shipped_to_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
    ]
