# Generated by Django 5.2.4 on 2025-07-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source_type',
            field=models.CharField(choices=[('marketplace', 'Marketplace'), ('auction', 'Auction')], default='marketplace', max_length=20),
        ),
    ]
