# Generated by Django 5.2.4 on 2025-07-26 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderitem_shipped_at'),
        ('stores', '0006_alter_storereferral_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storereferral'),
        ),
    ]
