# Generated by Django 5.2.4 on 2025-07-31 01:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_store_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_type',
            field=models.CharField(choices=[('none', 'None'), ('percent', 'Percent'), ('amount', 'Amount')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
