# Generated by Django 5.2.4 on 2025-07-31 04:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orderitem_discount_type_orderitem_discount_value'),
        ('stores', '0009_storefavorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='return',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='return',
            name='reason_description',
            field=models.TextField(blank=True, default='', help_text='Detailed explanation for the return'),
        ),
        migrations.AlterField(
            model_name='return',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='return',
            name='total_return_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='returnrefund',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='storeinventory',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_summary', to='stores.store'),
        ),
    ]
