# Generated by Django 5.2.4 on 2025-07-31 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_storeinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
