# Generated by Django 5.2.4 on 2025-08-01 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_returnitem_order_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='return',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status'], name='orders_retu_status_5626c0_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['buyer'], name='orders_retu_buyer_i_7becf4_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['created_at'], name='orders_retu_created_0e471a_idx'),
        ),
        migrations.AddConstraint(
            model_name='return',
            constraint=models.CheckConstraint(condition=models.Q(('total_return_amount__gte', 0)), name='return_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='return',
            constraint=models.CheckConstraint(condition=models.Q(('discount_applied__gte', 0)), name='return_discount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='return',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='return_refund_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='return',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__lte', models.F('total_return_amount'))), name='refund_lte_total'),
        ),
    ]
