# Generated by Django 5.2.5 on 2025-09-06 23:51

import django.core.validators
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_return_options_alter_return_tracking_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif']), orders.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['order', 'created_at'], name='orders_chat_order_i_a70717_idx'),
        ),
    ]
