# Generated by Django 5.2.9 on 2026-01-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='geo_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
