# Generated by Django 5.2.9 on 2026-01-08 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_shipment_shipment_number_and_more'),
        ('orders', '0026_shippingaddress_latitude_shippingaddress_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='current_shipment',
            field=models.ForeignKey(blank=True, help_text='The shipment this item is currently assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_items', to='logistics.shipment'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='Automatically set when shipped_to_warehouse becomes True', null=True),
        ),
    ]
