# Generated by Django 5.2.10 on 2026-01-16 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0047_alter_wheelspin_options_and_more'),
        ('orders', '0027_orderitem_current_shipment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Promo Code', 'verbose_name_plural': 'Promo Codes'},
        ),
        migrations.AddField(
            model_name='promocode',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='If set, only these users can use this code', related_name='exclusive_promo_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocode',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Associated campaign (if from wheel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_promo_codes', to='marketplace.campaign'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who created this code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free_shipping', 'Free Shipping')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='excluded_users',
            field=models.ManyToManyField(blank=True, help_text='Users who cannot use this code', related_name='excluded_from_promo_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocode',
            name='first_purchase_only',
            field=models.BooleanField(default=False, help_text="Only valid for user's first purchase"),
        ),
        migrations.AddField(
            model_name='promocode',
            name='max_uses',
            field=models.IntegerField(blank=True, help_text='Maximum number of times code can be used (null = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order total required', max_digits=10),
        ),
        migrations.AddField(
            model_name='promocode',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Creation'), ('campaign_wheel', 'Campaign Wheel Prize'), ('bulk_import', 'Bulk Import'), ('api', 'API Generated'), ('affiliate', 'Affiliate Program'), ('loyalty', 'Loyalty Reward')], db_index=True, default='manual', help_text='How this promo code was created', max_length=50),
        ),
        migrations.AddField(
            model_name='promocode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='valid_for_categories',
            field=models.ManyToManyField(blank=True, help_text='If set, code only applies to products in these categories', related_name='category_promo_codes', to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='valid_for_products',
            field=models.ManyToManyField(blank=True, help_text='If set, code only applies to these specific products', related_name='restricted_promo_codes', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='orders_prom_code_04587b_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='orders_prom_is_acti_4ca6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['source'], name='orders_prom_source_ef3370_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['campaign'], name='orders_prom_campaig_82ca9a_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['created_at'], name='orders_prom_created_bb7e5d_idx'),
        ),
    ]
