# Generated by Django 5.2.10 on 2026-01-17 13:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_country_flag_emoji'),
        ('orders', '0028_alter_promocode_options_promocode_allowed_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_currency',
            field=models.ForeignKey(blank=True, help_text='Currency used when setting shipping/discount (conversion tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_priced_in', to='accounts.currency'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_fx_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1.0'), help_text='FX rate snapshot used when converting to GMD', max_digits=18),
        ),
    ]
